package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log/slog"
	"strings"
	"text/template"
	"time"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

var (
	showVersion = flag.Bool("version", false, "print the version and exit")
)

const (
	contextPackage = protogen.GoImportPath("context")
)

func main() {
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-go-agserveri %v\n", release)
		return
	}
	protogen.Options{
		ParamFunc: flag.CommandLine.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		// 遍历所有的 .proto 文件
		for _, f := range gen.Files {
			// slog.Info(fmt.Sprintf("agserver: f.path:%s \n f.GoPackageName:%s \n Generate:%v", f.Desc.Path(), f.GoPackageName, f.Generate))
			if !f.Generate {
				continue
			}

			err := generateFile(gen, f)
			if err != nil {
				return err
			}
		}

		return nil
	})
}

// generateFile 为单个 .proto 文件生成代码
func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	filename := file.GeneratedFilenamePrefix + "_agserver.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	pf := parseProtoFile(g, file)
	protoFileJson, _ := json.MarshalIndent(pf, "", "    ")
	slog.Info(string(protoFileJson))

	// 文件头注释
	g.P("// Code generated by protoc-gen-go-agserver. DO NOT EDIT.")
	g.P(fmt.Sprintf("// Generate time: %s", time.Now().Format(time.DateTime)))
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-http %s", release))
	g.P("// - protoc             ", protocVersion(gen))

	if pf.Deprected {
		g.P("// ", pf.DescPath, " is a deprecated file.")
	} else {
		g.P("// source: ", pf.DescPath)
	}
	g.P()

	// 包名
	g.P("package ", file.GoPackageName)

	// imports
	g.P("var _ = new(", contextPackage.Ident("Context"), ")")

	// 模板生成
	tpl := serverTemplate
	tmpl, err := template.New(tpl).Parse(strings.TrimSpace(tpl))
	if err != nil {
		return err
	}

	err = tmpl.Execute(g, pf)
	if err != nil {
		return err
	}

	return nil

	// g.P("// Generate by agserver for", file.Desc.Path())
	// g.P("// GeneratedFilenamePrefix:", file.GeneratedFilenamePrefix)
	// g.P("// GoImportPath:", file.GoImportPath)
	// g.P("// GoPackageName:", file.GoPackageName)
	// g.P("// Services:", len(file.Services))
	// g.P("// Desc.Path:", file.Desc.Path())

	// option := file.Proto.GetOptions()
	// // opjson, _ := json.MarshalIndent(option, "", "    ")
	// opjson, _ := json.Marshal(option)
	// g.P("// Options:", fmt.Sprintf("%s", opjson))
	// g.P("// Deprecated:", option.GetDeprecated())

	// g.P()
	// g.P("// Generate time:", time.Now().Format(time.DateTime))

	// g.P()
	// g.P()

	// // 遍历Services
	// for _, service := range file.Services {
	// 	// 用例：
	// 	// import "google/protobuf/descriptor.proto";
	// 	// service xxx {
	// 	// option deprecated = true;
	// 	// }
	// 	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
	// 		g.P("// Deprecated: Do not use.")
	// 	}
	// 	g.P("// ==service:", service.GoName)
	// 	g.P("// GoName:", service.GoName)
	// 	g.P("// Desc.FullName:", service.Desc.FullName())

	// 	// type {{.ServiceType}}Server interface {
	// 	g.P(fmt.Sprintf("type %sServer interface {", service.GoName))

	// 	// 遍历方法
	// 	for _, m := range service.Methods {
	// 		g.P("// --method:", m.GoName)
	// 		g.P("// IsStreamingClien:", m.Desc.IsStreamingClient())
	// 		g.P("// IsStreamingServer:", m.Desc.IsStreamingServer())

	// 		request := g.QualifiedGoIdent(m.Input.GoIdent)
	// 		reply := g.QualifiedGoIdent(m.Output.GoIdent)
	// 		g.P("// Request:", request)
	// 		g.P("// Reply:", reply)

	// 		lds := m.Comments.LeadingDetached
	// 		for _, cm := range lds {
	// 			g.P("// Comment Leading Detached:\n",
	// 				cm.String())
	// 		}

	// 		g.P("// Comment Leading:", strings.TrimPrefix(strings.TrimSuffix(
	// 			m.Comments.Leading.String(), "\n"), "//"))
	// 		g.P("// Comment Trailing:", strings.TrimPrefix(strings.TrimSuffix(
	// 			m.Comments.Trailing.String(), "\n"), "//"))

	// 		// {{.Name}}(context.Context, *{{.Request}}) (*{{.Reply}}, error)
	// 		g.P(fmt.Sprintf("%s(context.Context, *%s) (*%s, error)", m.GoName, request, reply))
	// 	}

	// 	g.P("}")

	// }

}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}
