package model

import (
	"fmt"
	"github.com/aif-go/ag-core/contribute/agdb/conditonwhere"
	db "github.com/aif-go/ag-core/contribute/agdb/gormdb"
	"gopkg.in/yaml.v2"
	"time"
)

// TmMediaAct 表模型
// AUTOGENERATED: DO NOT EDIT
type TmMediaAct struct {
	Seq              int64     `gorm:"column:SEQ;primaryKey;not null" json:"Seq"`
	Cardno           string    `gorm:"column:CARDNO;size:19;index:TM_MEDIA_ACT_UNIUQE_1,priority:1" json:"Cardno"`
	AppId            string    `gorm:"column:APP_ID;size:10" json:"AppId"`
	NewCardno        string    `gorm:"column:NEW_CARDNO;size:19" json:"NewCardno"`
	BizDate          time.Time `gorm:"column:BIZ_DATE;index:INDEX1_TM_MEDOA_ACT,priority:1;index:INDEX2_TM_MEDIA_ACT,priority:2;index:TM_MEDIA_ACT_UNIUQE_1,priority:2" json:"BizDate"`
	ActionCd         string    `gorm:"column:ACTION_CD;size:2;index:INDEX1_TM_MEDOA_ACT,priority:2" json:"ActionCd"`
	ActStatus        string    `gorm:"column:ACT_STATUS;size:1" json:"ActStatus"`
	CardFetchMethod  string    `gorm:"column:CARD_FETCH_METHOD;size:1" json:"CardFetchMethod"`
	Address          string    `gorm:"column:ADDRESS;size:200;index:INDEX2_TM_MEDIA_ACT,priority:1" json:"Address"`
	City             string    `gorm:"column:CITY;size:40" json:"City"`
	CountryCd        string    `gorm:"column:COUNTRY_CD;size:3" json:"CountryCd"`
	District         string    `gorm:"column:DISTRICT;size:40" json:"District"`
	State            string    `gorm:"column:STATE;size:40" json:"State"`
	Zip              string    `gorm:"column:ZIP;size:10" json:"Zip"`
	Gender           string    `gorm:"column:Gender;size:1" json:"Gender"`
	Name             string    `gorm:"column:NAME;size:80" json:"Name"`
	CorpName         string    `gorm:"column:CORP_NAME;size:80" json:"CorpName"`
	BscSuppInd       string    `gorm:"column:BSC_SUPP_IND;size:1" json:"BscSuppInd"`
	IdType           string    `gorm:"column:ID_TYPE;size:1" json:"IdType"`
	IdNo             string    `gorm:"column:ID_NO;size:30" json:"IdNo"`
	MobileNo         string    `gorm:"column:MOBILE_NO;size:20" json:"MobileNo"`
	Phone            string    `gorm:"column:PHONE;size:20" json:"Phone"`
	OwningBranch     string    `gorm:"column:OWNING_BRANCH;size:12" json:"OwningBranch"`
	BillingCycle     string    `gorm:"column:BILLING_CYCLE;size:2" json:"BillingCycle"`
	CurrCd           string    `gorm:"column:CURR_CD;size:3" json:"CurrCd"`
	CreditLimit      int64     `gorm:"column:CREDIT_LIMIT" json:"CreditLimit"`
	DualCurrCd       string    `gorm:"column:DUAL_CURR_CD;size:3" json:"DualCurrCd"`
	DualCreditLimit  int64     `gorm:"column:DUAL_CREDIT_LIMIT" json:"DualCreditLimit"`
	IsUrgentCard     string    `gorm:"column:IS_URGENT_CARD;size:1" json:"IsUrgentCard"`
	JpaVersion       int       `gorm:"column:JPA_VERSION" json:"JpaVersion"`
	CreatedTime      time.Time `gorm:"column:CREATED_TIME;AUTOCREATETIME" json:"CreatedTime"`
	LastModifiedTime time.Time `gorm:"column:LAST_MODIFIED_TIME;AUTOUPDATETIME" json:"LastModifiedTime"`
	Org              string    `gorm:"column:ORG;size:12" json:"Org"`
	CardMailerInd    string    `gorm:"column:CARD_MAILER_IND;size:1" json:"CardMailerInd"`
	EncodeName       string    `gorm:"column:ENCODE_NAME;size:160" json:"EncodeName"`
	EncodeAddress    string    `gorm:"column:ENCODE_ADDRESS;size:400" json:"EncodeAddress"`
}

// TmMediaActPrimaryKey 单主键类型别名
type TmMediaActPrimaryKey int64

// TableName 返回表名
func (tmMediaAct *TmMediaAct) TableName() string {
	return "TM_MEDIA_ACT"
}

// Clone 克隆对象
func (tmMediaAct *TmMediaAct) Clone() *TmMediaAct {
	if tmMediaAct == nil {
		return nil
	}
	return &TmMediaAct{
		Seq:              tmMediaAct.Seq,
		Cardno:           tmMediaAct.Cardno,
		AppId:            tmMediaAct.AppId,
		NewCardno:        tmMediaAct.NewCardno,
		BizDate:          tmMediaAct.BizDate,
		ActionCd:         tmMediaAct.ActionCd,
		ActStatus:        tmMediaAct.ActStatus,
		CardFetchMethod:  tmMediaAct.CardFetchMethod,
		Address:          tmMediaAct.Address,
		City:             tmMediaAct.City,
		CountryCd:        tmMediaAct.CountryCd,
		District:         tmMediaAct.District,
		State:            tmMediaAct.State,
		Zip:              tmMediaAct.Zip,
		Gender:           tmMediaAct.Gender,
		Name:             tmMediaAct.Name,
		CorpName:         tmMediaAct.CorpName,
		BscSuppInd:       tmMediaAct.BscSuppInd,
		IdType:           tmMediaAct.IdType,
		IdNo:             tmMediaAct.IdNo,
		MobileNo:         tmMediaAct.MobileNo,
		Phone:            tmMediaAct.Phone,
		OwningBranch:     tmMediaAct.OwningBranch,
		BillingCycle:     tmMediaAct.BillingCycle,
		CurrCd:           tmMediaAct.CurrCd,
		CreditLimit:      tmMediaAct.CreditLimit,
		DualCurrCd:       tmMediaAct.DualCurrCd,
		DualCreditLimit:  tmMediaAct.DualCreditLimit,
		IsUrgentCard:     tmMediaAct.IsUrgentCard,
		JpaVersion:       tmMediaAct.JpaVersion,
		CreatedTime:      tmMediaAct.CreatedTime,
		LastModifiedTime: tmMediaAct.LastModifiedTime,
		Org:              tmMediaAct.Org,
		CardMailerInd:    tmMediaAct.CardMailerInd,
		EncodeName:       tmMediaAct.EncodeName,
		EncodeAddress:    tmMediaAct.EncodeAddress,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (tmMediaAct *TmMediaAct) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if tmMediaAct == nil {
		return nil, nil, fmt.Errorf("tmMediaAct is nil")
	}

	var cols []string
	var vals []interface{}

	// generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false

	// Seq - 主键，索引列
	if !filterPrimary {
		isZero := tmMediaAct.Seq == 0
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "SEQ")
			vals = append(vals, tmMediaAct.Seq)
		}
	}

	// Cardno - 索引列
	if !filterIndex {
		isZero := tmMediaAct.Cardno == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "CARDNO")
			vals = append(vals, tmMediaAct.Cardno)
		}
	}

	// AppId - 普通列
	generalColZeroVal = tmMediaAct.AppId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "APP_ID")
		vals = append(vals, tmMediaAct.AppId)
	}

	// NewCardno - 普通列
	generalColZeroVal = tmMediaAct.NewCardno == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "NEW_CARDNO")
		vals = append(vals, tmMediaAct.NewCardno)
	}

	// BizDate - 索引列
	if !filterIndex {
		isZero := tmMediaAct.BizDate.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "BIZ_DATE")
			vals = append(vals, tmMediaAct.BizDate)
		}
	}

	// ActionCd - 索引列
	if !filterIndex {
		isZero := tmMediaAct.ActionCd == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "ACTION_CD")
			vals = append(vals, tmMediaAct.ActionCd)
		}
	}

	// ActStatus - 普通列
	generalColZeroVal = tmMediaAct.ActStatus == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ACT_STATUS")
		vals = append(vals, tmMediaAct.ActStatus)
	}

	// CardFetchMethod - 普通列
	generalColZeroVal = tmMediaAct.CardFetchMethod == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARD_FETCH_METHOD")
		vals = append(vals, tmMediaAct.CardFetchMethod)
	}

	// Address - 索引列
	if !filterIndex {
		isZero := tmMediaAct.Address == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "ADDRESS")
			vals = append(vals, tmMediaAct.Address)
		}
	}

	// City - 普通列
	generalColZeroVal = tmMediaAct.City == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CITY")
		vals = append(vals, tmMediaAct.City)
	}

	// CountryCd - 普通列
	generalColZeroVal = tmMediaAct.CountryCd == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "COUNTRY_CD")
		vals = append(vals, tmMediaAct.CountryCd)
	}

	// District - 普通列
	generalColZeroVal = tmMediaAct.District == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "DISTRICT")
		vals = append(vals, tmMediaAct.District)
	}

	// State - 普通列
	generalColZeroVal = tmMediaAct.State == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "STATE")
		vals = append(vals, tmMediaAct.State)
	}

	// Zip - 普通列
	generalColZeroVal = tmMediaAct.Zip == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ZIP")
		vals = append(vals, tmMediaAct.Zip)
	}

	// Gender - 普通列
	generalColZeroVal = tmMediaAct.Gender == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "Gender")
		vals = append(vals, tmMediaAct.Gender)
	}

	// Name - 普通列
	generalColZeroVal = tmMediaAct.Name == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "NAME")
		vals = append(vals, tmMediaAct.Name)
	}

	// CorpName - 普通列
	generalColZeroVal = tmMediaAct.CorpName == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CORP_NAME")
		vals = append(vals, tmMediaAct.CorpName)
	}

	// BscSuppInd - 普通列
	generalColZeroVal = tmMediaAct.BscSuppInd == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "BSC_SUPP_IND")
		vals = append(vals, tmMediaAct.BscSuppInd)
	}

	// IdType - 普通列
	generalColZeroVal = tmMediaAct.IdType == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ID_TYPE")
		vals = append(vals, tmMediaAct.IdType)
	}

	// IdNo - 普通列
	generalColZeroVal = tmMediaAct.IdNo == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ID_NO")
		vals = append(vals, tmMediaAct.IdNo)
	}

	// MobileNo - 普通列
	generalColZeroVal = tmMediaAct.MobileNo == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "MOBILE_NO")
		vals = append(vals, tmMediaAct.MobileNo)
	}

	// Phone - 普通列
	generalColZeroVal = tmMediaAct.Phone == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "PHONE")
		vals = append(vals, tmMediaAct.Phone)
	}

	// OwningBranch - 普通列
	generalColZeroVal = tmMediaAct.OwningBranch == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "OWNING_BRANCH")
		vals = append(vals, tmMediaAct.OwningBranch)
	}

	// BillingCycle - 普通列
	generalColZeroVal = tmMediaAct.BillingCycle == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "BILLING_CYCLE")
		vals = append(vals, tmMediaAct.BillingCycle)
	}

	// CurrCd - 普通列
	generalColZeroVal = tmMediaAct.CurrCd == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CURR_CD")
		vals = append(vals, tmMediaAct.CurrCd)
	}

	// CreditLimit - 普通列
	generalColZeroVal = tmMediaAct.CreditLimit == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CREDIT_LIMIT")
		vals = append(vals, tmMediaAct.CreditLimit)
	}

	// DualCurrCd - 普通列
	generalColZeroVal = tmMediaAct.DualCurrCd == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "DUAL_CURR_CD")
		vals = append(vals, tmMediaAct.DualCurrCd)
	}

	// DualCreditLimit - 普通列
	generalColZeroVal = tmMediaAct.DualCreditLimit == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "DUAL_CREDIT_LIMIT")
		vals = append(vals, tmMediaAct.DualCreditLimit)
	}

	// IsUrgentCard - 普通列
	generalColZeroVal = tmMediaAct.IsUrgentCard == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "IS_URGENT_CARD")
		vals = append(vals, tmMediaAct.IsUrgentCard)
	}

	// JpaVersion - 普通列
	generalColZeroVal = tmMediaAct.JpaVersion == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "JPA_VERSION")
		vals = append(vals, tmMediaAct.JpaVersion)
	}

	// CreatedTime - 特殊列，用于自动创建时间
	if !filterSpecial {
		isZero := tmMediaAct.CreatedTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "CREATED_TIME")
			vals = append(vals, tmMediaAct.CreatedTime)
		}
	}

	// LastModifiedTime - 特殊列，用于特殊用途
	if !filterSpecial {
		isZero := tmMediaAct.LastModifiedTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "LAST_MODIFIED_TIME")
			vals = append(vals, tmMediaAct.LastModifiedTime)
		}
	}

	// Org - 普通列
	generalColZeroVal = tmMediaAct.Org == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ORG")
		vals = append(vals, tmMediaAct.Org)
	}

	// CardMailerInd - 普通列
	generalColZeroVal = tmMediaAct.CardMailerInd == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARD_MAILER_IND")
		vals = append(vals, tmMediaAct.CardMailerInd)
	}

	// EncodeName - 普通列
	generalColZeroVal = tmMediaAct.EncodeName == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ENCODE_NAME")
		vals = append(vals, tmMediaAct.EncodeName)
	}

	// EncodeAddress - 普通列
	generalColZeroVal = tmMediaAct.EncodeAddress == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ENCODE_ADDRESS")
		vals = append(vals, tmMediaAct.EncodeAddress)
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (tmMediaAct *TmMediaAct) ToString() string {
	if tmMediaAct == nil {
		return ""
	}
	return fmt.Sprintf("TmMediaAct:(%+v)", *tmMediaAct)
}

// TmMediaActAllowUpdateCols 支持更新的列名列表
var TmMediaActAllowUpdateCols = []string{"SEQ", "CARDNO", "APP_ID", "NEW_CARDNO", "BIZ_DATE", "ACTION_CD", "ACT_STATUS", "CARD_FETCH_METHOD", "ADDRESS", "CITY", "COUNTRY_CD", "DISTRICT", "STATE", "ZIP", "Gender", "NAME", "CORP_NAME", "BSC_SUPP_IND", "ID_TYPE", "ID_NO", "MOBILE_NO", "PHONE", "OWNING_BRANCH", "BILLING_CYCLE", "CURR_CD", "CREDIT_LIMIT", "DUAL_CURR_CD", "DUAL_CREDIT_LIMIT", "IS_URGENT_CARD", "JPA_VERSION", "CREATED_TIME", "LAST_MODIFIED_TIME", "ORG", "CARD_MAILER_IND", "ENCODE_NAME", "ENCODE_ADDRESS"}

// TmMediaActIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var TmMediaActIndexLeadingCols = []string{"SEQ", "BIZ_DATE", "ADDRESS", "CARDNO"}

// TmMediaActNoPageQueryArg NoPageQuery 查询参数
type TmMediaActNoPageQueryArg struct {
	FieldMask *conditonwhere.FieldMask
	BizDate   time.Time
	ActionCd  string
}

func (tmMediaActNoPageQueryArg *TmMediaActNoPageQueryArg) WithBizDate(BizDate time.Time) *TmMediaActNoPageQueryArg {
	tmMediaActNoPageQueryArg.BizDate = BizDate
	tmMediaActNoPageQueryArg.FieldMask.Set("BizDate")
	return tmMediaActNoPageQueryArg
}

func (tmMediaActNoPageQueryArg *TmMediaActNoPageQueryArg) WithActionCd(ActionCd string) *TmMediaActNoPageQueryArg {
	tmMediaActNoPageQueryArg.ActionCd = ActionCd
	tmMediaActNoPageQueryArg.FieldMask.Set("ActionCd")
	return tmMediaActNoPageQueryArg
}

// ConvertToMap 将参数转换为map
func (tmMediaActNoPageQueryArg *TmMediaActNoPageQueryArg) ConvertToMap() map[string]interface{} {
	if tmMediaActNoPageQueryArg == nil {
		return nil
	}
	return map[string]interface{}{
		"BizDate":  tmMediaActNoPageQueryArg.BizDate,
		"ActionCd": tmMediaActNoPageQueryArg.ActionCd,
	}
}

// TmMediaActNoPageQueryRes NoPageQuery 查询结果
type TmMediaActNoPageQueryRes struct {
	Cardno    string `gorm:"column:CARDNO" json:"Cardno"`
	AppId     string `gorm:"column:APP_ID" json:"AppId"`
	NewCardno string `gorm:"column:NEW_CARDNO" json:"NewCardno"`
}

// TmMediaActXxxxxArg Xxxxx 查询参数
type TmMediaActXxxxxArg struct {
	db.Page
	FieldMask    *conditonwhere.FieldMask
	BizDate      time.Time
	ActionCd     string
	Address      string
	BizDateSlice []time.Time
}

func (tmMediaActXxxxxArg *TmMediaActXxxxxArg) WithBizDate(BizDate time.Time) *TmMediaActXxxxxArg {
	tmMediaActXxxxxArg.BizDate = BizDate
	tmMediaActXxxxxArg.FieldMask.Set("BizDate")
	return tmMediaActXxxxxArg
}

func (tmMediaActXxxxxArg *TmMediaActXxxxxArg) WithActionCd(ActionCd string) *TmMediaActXxxxxArg {
	tmMediaActXxxxxArg.ActionCd = ActionCd
	tmMediaActXxxxxArg.FieldMask.Set("ActionCd")
	return tmMediaActXxxxxArg
}

func (tmMediaActXxxxxArg *TmMediaActXxxxxArg) WithAddress(Address string) *TmMediaActXxxxxArg {
	tmMediaActXxxxxArg.Address = Address
	tmMediaActXxxxxArg.FieldMask.Set("Address")
	return tmMediaActXxxxxArg
}

func (tmMediaActXxxxxArg *TmMediaActXxxxxArg) WithBizDateSlice(BizDateSlice []time.Time) *TmMediaActXxxxxArg {
	tmMediaActXxxxxArg.BizDateSlice = BizDateSlice
	tmMediaActXxxxxArg.FieldMask.Set("BizDateSlice")
	return tmMediaActXxxxxArg
}

// ConvertToMap 将参数转换为map
func (tmMediaActXxxxxArg *TmMediaActXxxxxArg) ConvertToMap() map[string]interface{} {
	if tmMediaActXxxxxArg == nil {
		return nil
	}
	return map[string]interface{}{
		"Page":         tmMediaActXxxxxArg.Page,
		"BizDate":      tmMediaActXxxxxArg.BizDate,
		"ActionCd":     tmMediaActXxxxxArg.ActionCd,
		"Address":      tmMediaActXxxxxArg.Address,
		"BizDateSlice": tmMediaActXxxxxArg.BizDateSlice,
	}
}

// TmMediaActXxxxxRes Xxxxx 查询结果
type TmMediaActXxxxxRes struct {
	Cardno    string `gorm:"column:CARDNO" json:"Cardno"`
	AppId     string `gorm:"column:APP_ID" json:"AppId"`
	NewCardno string `gorm:"column:NEW_CARDNO" json:"NewCardno"`
}

// TmMediaActXxxxxPageRes Xxxxx 分页查询结果
type TmMediaActXxxxxPageRes struct {
	db.PageResult
	ResultList []*TmMediaActXxxxxRes
}

// WhereDataToYAMLCache WhereDataYAML缓存
var TmMediaActWhereDataToYAMLCache = map[string]string{
	"NoPageQuery": `conditions:
- expr: BIZ_DATE = @BizDate
- expr: ACTION_CD = @ActionCd
operator: AND
`,
	"Xxxxx": `conditions:
- conditions:
  - expr: BIZ_DATE = @BizDate
  - expr: ACTION_CD = @ActionCd
  operator: AND
- conditions:
  - expr: ADDRESS = @Address
  - expr: BIZ_DATE in @BizDateSlice
  operator: AND
operator: OR
`,
}

var TmMediaActConditionMap = map[string]*conditonwhere.MaskWhereCondition{}

// 初始注册自定义函数的condition
func init() {
	for key, whereDataYaml := range TmMediaActWhereDataToYAMLCache {
		var newData map[interface{}]interface{}
		yaml.Unmarshal([]byte(whereDataYaml), &newData)
		TmMediaActConditionMap[key] = conditonwhere.ParseWhereCondition(newData)
	}
}
