package model
import (
	"fmt"
	"github.com/shopspring/decimal"
	"time"
)
// TmNo 表模型
// AUTOGENERATED: DO NOT EDIT
type TmNo struct {
	TenantId int64 `gorm:"column:tenant_id" json:"TenantId"`
	StudentNo string `gorm:"column:student_no;size:20" json:"StudentNo"`
	Name string `gorm:"column:name;size:20" json:"Name"`
	Address string `gorm:"column:address;size:100" json:"Address"`
	Phone string `gorm:"column:phone;size:11" json:"Phone"`
	ClassId string `gorm:"column:class_id;size:2" json:"ClassId"`
	CardNo string `gorm:"column:card_no;size:20" json:"CardNo"`
	Score decimal.Decimal `gorm:"column:score;type:decimal(10,2);precision:10;scale:2" json:"Score"`
	EnrollDate *time.Time `gorm:"column:enroll_date" json:"EnrollDate"`
	IsGraduate bool `gorm:"column:is_graduate" json:"IsGraduate"`
	JpaVersion int64 `gorm:"column:jpa_version" json:"JpaVersion"`
	CreateTime time.Time `gorm:"column:create_time;AUTOCREATETIME" json:"CreateTime"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;AUTOUPDATETIME" json:"LastUpdateTime"`
}

// TmNoPrimarkey 多主键结构体
type TmNoPrimarkey struct {

}

// TableName 返回表名
func (tmNo *TmNo) TableName() string {
	return "tm_no"
}

// Clone 克隆对象
func (tmNo *TmNo) Clone() *TmNo {
	if tmNo == nil {
		return nil
	}
	return &TmNo{
		TenantId: tmNo.TenantId,
		StudentNo: tmNo.StudentNo,
		Name: tmNo.Name,
		Address: tmNo.Address,
		Phone: tmNo.Phone,
		ClassId: tmNo.ClassId,
		CardNo: tmNo.CardNo,
		Score: tmNo.Score,
		EnrollDate: tmNo.EnrollDate,
		IsGraduate: tmNo.IsGraduate,
		JpaVersion: tmNo.JpaVersion,
		CreateTime: tmNo.CreateTime,
		LastUpdateTime: tmNo.LastUpdateTime,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (tmNo *TmNo) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if tmNo == nil {
		return nil, nil, fmt.Errorf("tmNo is nil")
	}

	var cols []string
	var vals []interface{}

 // generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false
	

	// TenantId - 普通列
	generalColZeroVal = tmNo.TenantId == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "tenant_id")
		vals = append(vals, tmNo.TenantId)
	}

	// StudentNo - 普通列
	generalColZeroVal = tmNo.StudentNo == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "student_no")
		vals = append(vals, tmNo.StudentNo)
	}

	// Name - 普通列
	generalColZeroVal = tmNo.Name == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "name")
		vals = append(vals, tmNo.Name)
	}

	// Address - 普通列
	generalColZeroVal = tmNo.Address == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "address")
		vals = append(vals, tmNo.Address)
	}

	// Phone - 普通列
	generalColZeroVal = tmNo.Phone == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "phone")
		vals = append(vals, tmNo.Phone)
	}

	// ClassId - 普通列
	generalColZeroVal = tmNo.ClassId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "class_id")
		vals = append(vals, tmNo.ClassId)
	}

	// CardNo - 普通列
	generalColZeroVal = tmNo.CardNo == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "card_no")
		vals = append(vals, tmNo.CardNo)
	}

	// Score - 普通列
	generalColZeroVal = tmNo.Score.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "score")
		vals = append(vals, tmNo.Score)
	}

	// EnrollDate - 普通列
	generalColZeroVal = tmNo.EnrollDate == nil
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "enroll_date")
		vals = append(vals, tmNo.EnrollDate)
	}

	// IsGraduate - 普通列
	generalColZeroVal = !tmNo.IsGraduate
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "is_graduate")
		vals = append(vals, tmNo.IsGraduate)
	}

	// JpaVersion - 特殊列，用于乐观锁
	if !filterSpecial {
		isZero := tmNo.JpaVersion == 0
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "jpa_version")
			vals = append(vals, tmNo.JpaVersion)
		}
	}

	// CreateTime - 特殊列，用于自动创建时间
	if !filterSpecial {
		isZero := tmNo.CreateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "create_time")
			vals = append(vals, tmNo.CreateTime)
		}
	}

	// LastUpdateTime - 特殊列，用于自动更新时间
	if !filterSpecial {
		isZero := tmNo.LastUpdateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "last_update_time")
			vals = append(vals, tmNo.LastUpdateTime)
		}
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (tmNo *TmNo) ToString() string {
	if tmNo == nil {
		return ""
	}
	return fmt.Sprintf("TmNo:(%+v)", *tmNo)
}

// TmNoAllowUpdateCols 支持更新的列名列表
var TmNoAllowUpdateCols = []string{"class_id", "card_no"}



