package model
import (
	"fmt"
	"github.com/aif-go/ag-core/contribute/agdb/conditonwhere"
	"gopkg.in/yaml.v2"
	"time"
)
// Tbl3dsRequest 表模型
// AUTOGENERATED: DO NOT EDIT
type Tbl3dsRequest struct {
	Id int64 `gorm:"column:ID;primaryKey;not null" json:"Id"`
	ClusterId string `gorm:"column:CLUSTER_ID;primaryKey;not null" json:"ClusterId"`
	TransactionType string `gorm:"column:TRANSACTION_TYPE;index:IDX_RRN,priority:3" json:"TransactionType"`
	OrderId string `gorm:"column:ORDER_ID;index:IDX_ORDER_ID,priority:1" json:"OrderId"`
	GatewayServiceKey string `gorm:"column:GATEWAY_SERVICE_KEY" json:"GatewayServiceKey"`
	GlobalTraceNo string `gorm:"column:GLOBAL_TRACE_NO" json:"GlobalTraceNo"`
	Pan string `gorm:"column:PAN" json:"Pan"`
	ProcessingCode string `gorm:"column:PROCESSING_CODE" json:"ProcessingCode"`
	OrderAmount int64 `gorm:"column:ORDER_AMOUNT" json:"OrderAmount"`
	TransactionAmount int64 `gorm:"column:TRANSACTION_AMOUNT" json:"TransactionAmount"`
	BillingAmount int64 `gorm:"column:BILLING_AMOUNT" json:"BillingAmount"`
	TransmissionDatetime string `gorm:"column:TRANSMISSION_DATETIME" json:"TransmissionDatetime"`
	ConversionRateBilling string `gorm:"column:CONVERSION_RATE_BILLING" json:"ConversionRateBilling"`
	Stan string `gorm:"column:STAN" json:"Stan"`
	LocalTime string `gorm:"column:LOCAL_TIME" json:"LocalTime"`
	LocalDate string `gorm:"column:LOCAL_DATE" json:"LocalDate"`
	Mcc string `gorm:"column:MCC" json:"Mcc"`
	AcquiringInstCountryCode string `gorm:"column:ACQUIRING_INST_COUNTRY_CODE" json:"AcquiringInstCountryCode"`
	PosEntryMode string `gorm:"column:POS_ENTRY_MODE" json:"PosEntryMode"`
	PosConditionCode string `gorm:"column:POS_CONDITION_CODE" json:"PosConditionCode"`
	PosPinCaptureCode string `gorm:"column:POS_PIN_CAPTURE_CODE" json:"PosPinCaptureCode"`
	AcquiringInstitution string `gorm:"column:ACQUIRING_INSTITUTION" json:"AcquiringInstitution"`
	RetrievalReferenceNumber string `gorm:"column:RETRIEVAL_REFERENCE_NUMBER;index:IDX_RRN,priority:1" json:"RetrievalReferenceNumber"`
	TerminalId string `gorm:"column:TERMINAL_ID" json:"TerminalId"`
	MerchantId string `gorm:"column:MERCHANT_ID;index:IDX_ORDER_ID,priority:2;index:IDX_RRN,priority:2" json:"MerchantId"`
	CardAcceptorLocation string `gorm:"column:CARD_ACCEPTOR_LOCATION" json:"CardAcceptorLocation"`
	OrderCurrency string `gorm:"column:ORDER_CURRENCY" json:"OrderCurrency"`
	TransactionCurrency string `gorm:"column:TRANSACTION_CURRENCY" json:"TransactionCurrency"`
	BillingCurrency string `gorm:"column:BILLING_CURRENCY" json:"BillingCurrency"`
	AdditionalPosData string `gorm:"column:ADDITIONAL_POS_DATA" json:"AdditionalPosData"`
	CardType string `gorm:"column:CARD_TYPE" json:"CardType"`
	DccFlag string `gorm:"column:DCC_FLAG" json:"DccFlag"`
	KeyDatetime string `gorm:"column:KEY_DATETIME" json:"KeyDatetime"`
	DeviceType string `gorm:"column:DEVICE_TYPE" json:"DeviceType"`
	InterfaceVersion string `gorm:"column:INTERFACE_VERSION" json:"InterfaceVersion"`
	Ip string `gorm:"column:IP" json:"Ip"`
	RiskServiceFlag string `gorm:"column:RISK_SERVICE_FLAG" json:"RiskServiceFlag"`
	PaymentType string `gorm:"column:PAYMENT_TYPE" json:"PaymentType"`
	CardholderCountry string `gorm:"column:CARDHOLDER_COUNTRY" json:"CardholderCountry"`
	CardholderAddress string `gorm:"column:CARDHOLDER_ADDRESS" json:"CardholderAddress"`
	CardholderName string `gorm:"column:CARDHOLDER_NAME" json:"CardholderName"`
	CardholderState string `gorm:"column:CARDHOLDER_STATE" json:"CardholderState"`
	CardholderCity string `gorm:"column:CARDHOLDER_CITY" json:"CardholderCity"`
	CardholderZipCode string `gorm:"column:CARDHOLDER_ZIP_CODE" json:"CardholderZipCode"`
	CardholderPhone string `gorm:"column:CARDHOLDER_PHONE" json:"CardholderPhone"`
	CardholderEmail string `gorm:"column:CARDHOLDER_EMAIL" json:"CardholderEmail"`
	Reserved1 string `gorm:"column:RESERVED_1" json:"Reserved1"`
	Reserved2 string `gorm:"column:RESERVED_2" json:"Reserved2"`
	InsertTimestamp time.Time `gorm:"column:INSERT_TIMESTAMP;AUTOCREATETIME;index:IDX_INSERT_TIMESTAMP,priority:1" json:"InsertTimestamp"`
	InsertUser string `gorm:"column:INSERT_USER" json:"InsertUser"`
}

// Tbl3dsRequestPrimarkey 多主键结构体
type Tbl3dsRequestPrimarkey struct {
	Id int64
	ClusterId string
}

// TableName 返回表名
func (tbl3dsRequest *Tbl3dsRequest) TableName() string {
	return "tbl_3ds_request"
}

// Clone 克隆对象
func (tbl3dsRequest *Tbl3dsRequest) Clone() *Tbl3dsRequest {
	if tbl3dsRequest == nil {
		return nil
	}
	return &Tbl3dsRequest{
		Id: tbl3dsRequest.Id,
		ClusterId: tbl3dsRequest.ClusterId,
		TransactionType: tbl3dsRequest.TransactionType,
		OrderId: tbl3dsRequest.OrderId,
		GatewayServiceKey: tbl3dsRequest.GatewayServiceKey,
		GlobalTraceNo: tbl3dsRequest.GlobalTraceNo,
		Pan: tbl3dsRequest.Pan,
		ProcessingCode: tbl3dsRequest.ProcessingCode,
		OrderAmount: tbl3dsRequest.OrderAmount,
		TransactionAmount: tbl3dsRequest.TransactionAmount,
		BillingAmount: tbl3dsRequest.BillingAmount,
		TransmissionDatetime: tbl3dsRequest.TransmissionDatetime,
		ConversionRateBilling: tbl3dsRequest.ConversionRateBilling,
		Stan: tbl3dsRequest.Stan,
		LocalTime: tbl3dsRequest.LocalTime,
		LocalDate: tbl3dsRequest.LocalDate,
		Mcc: tbl3dsRequest.Mcc,
		AcquiringInstCountryCode: tbl3dsRequest.AcquiringInstCountryCode,
		PosEntryMode: tbl3dsRequest.PosEntryMode,
		PosConditionCode: tbl3dsRequest.PosConditionCode,
		PosPinCaptureCode: tbl3dsRequest.PosPinCaptureCode,
		AcquiringInstitution: tbl3dsRequest.AcquiringInstitution,
		RetrievalReferenceNumber: tbl3dsRequest.RetrievalReferenceNumber,
		TerminalId: tbl3dsRequest.TerminalId,
		MerchantId: tbl3dsRequest.MerchantId,
		CardAcceptorLocation: tbl3dsRequest.CardAcceptorLocation,
		OrderCurrency: tbl3dsRequest.OrderCurrency,
		TransactionCurrency: tbl3dsRequest.TransactionCurrency,
		BillingCurrency: tbl3dsRequest.BillingCurrency,
		AdditionalPosData: tbl3dsRequest.AdditionalPosData,
		CardType: tbl3dsRequest.CardType,
		DccFlag: tbl3dsRequest.DccFlag,
		KeyDatetime: tbl3dsRequest.KeyDatetime,
		DeviceType: tbl3dsRequest.DeviceType,
		InterfaceVersion: tbl3dsRequest.InterfaceVersion,
		Ip: tbl3dsRequest.Ip,
		RiskServiceFlag: tbl3dsRequest.RiskServiceFlag,
		PaymentType: tbl3dsRequest.PaymentType,
		CardholderCountry: tbl3dsRequest.CardholderCountry,
		CardholderAddress: tbl3dsRequest.CardholderAddress,
		CardholderName: tbl3dsRequest.CardholderName,
		CardholderState: tbl3dsRequest.CardholderState,
		CardholderCity: tbl3dsRequest.CardholderCity,
		CardholderZipCode: tbl3dsRequest.CardholderZipCode,
		CardholderPhone: tbl3dsRequest.CardholderPhone,
		CardholderEmail: tbl3dsRequest.CardholderEmail,
		Reserved1: tbl3dsRequest.Reserved1,
		Reserved2: tbl3dsRequest.Reserved2,
		InsertTimestamp: tbl3dsRequest.InsertTimestamp,
		InsertUser: tbl3dsRequest.InsertUser,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (tbl3dsRequest *Tbl3dsRequest) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if tbl3dsRequest == nil {
		return nil, nil, fmt.Errorf("tbl3dsRequest is nil")
	}

	var cols []string
	var vals []interface{}

 // generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false
	

	// Id - 主键，索引列
	if !filterPrimary {
		isZero := tbl3dsRequest.Id == 0
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "ID")
			vals = append(vals, tbl3dsRequest.Id)
		}
	}

	// ClusterId - 主键，索引列
	if !filterPrimary {
		isZero := tbl3dsRequest.ClusterId == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "CLUSTER_ID")
			vals = append(vals, tbl3dsRequest.ClusterId)
		}
	}

	// TransactionType - 索引列
	if !filterIndex {
		isZero := tbl3dsRequest.TransactionType == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "TRANSACTION_TYPE")
			vals = append(vals, tbl3dsRequest.TransactionType)
		}
	}

	// OrderId - 索引列
	if !filterIndex {
		isZero := tbl3dsRequest.OrderId == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "ORDER_ID")
			vals = append(vals, tbl3dsRequest.OrderId)
		}
	}

	// GatewayServiceKey - 普通列
	generalColZeroVal = tbl3dsRequest.GatewayServiceKey == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "GATEWAY_SERVICE_KEY")
		vals = append(vals, tbl3dsRequest.GatewayServiceKey)
	}

	// GlobalTraceNo - 普通列
	generalColZeroVal = tbl3dsRequest.GlobalTraceNo == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "GLOBAL_TRACE_NO")
		vals = append(vals, tbl3dsRequest.GlobalTraceNo)
	}

	// Pan - 普通列
	generalColZeroVal = tbl3dsRequest.Pan == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "PAN")
		vals = append(vals, tbl3dsRequest.Pan)
	}

	// ProcessingCode - 普通列
	generalColZeroVal = tbl3dsRequest.ProcessingCode == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "PROCESSING_CODE")
		vals = append(vals, tbl3dsRequest.ProcessingCode)
	}

	// OrderAmount - 普通列
	generalColZeroVal = tbl3dsRequest.OrderAmount == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ORDER_AMOUNT")
		vals = append(vals, tbl3dsRequest.OrderAmount)
	}

	// TransactionAmount - 普通列
	generalColZeroVal = tbl3dsRequest.TransactionAmount == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "TRANSACTION_AMOUNT")
		vals = append(vals, tbl3dsRequest.TransactionAmount)
	}

	// BillingAmount - 普通列
	generalColZeroVal = tbl3dsRequest.BillingAmount == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "BILLING_AMOUNT")
		vals = append(vals, tbl3dsRequest.BillingAmount)
	}

	// TransmissionDatetime - 普通列
	generalColZeroVal = tbl3dsRequest.TransmissionDatetime == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "TRANSMISSION_DATETIME")
		vals = append(vals, tbl3dsRequest.TransmissionDatetime)
	}

	// ConversionRateBilling - 普通列
	generalColZeroVal = tbl3dsRequest.ConversionRateBilling == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CONVERSION_RATE_BILLING")
		vals = append(vals, tbl3dsRequest.ConversionRateBilling)
	}

	// Stan - 普通列
	generalColZeroVal = tbl3dsRequest.Stan == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "STAN")
		vals = append(vals, tbl3dsRequest.Stan)
	}

	// LocalTime - 普通列
	generalColZeroVal = tbl3dsRequest.LocalTime == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "LOCAL_TIME")
		vals = append(vals, tbl3dsRequest.LocalTime)
	}

	// LocalDate - 普通列
	generalColZeroVal = tbl3dsRequest.LocalDate == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "LOCAL_DATE")
		vals = append(vals, tbl3dsRequest.LocalDate)
	}

	// Mcc - 普通列
	generalColZeroVal = tbl3dsRequest.Mcc == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "MCC")
		vals = append(vals, tbl3dsRequest.Mcc)
	}

	// AcquiringInstCountryCode - 普通列
	generalColZeroVal = tbl3dsRequest.AcquiringInstCountryCode == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ACQUIRING_INST_COUNTRY_CODE")
		vals = append(vals, tbl3dsRequest.AcquiringInstCountryCode)
	}

	// PosEntryMode - 普通列
	generalColZeroVal = tbl3dsRequest.PosEntryMode == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "POS_ENTRY_MODE")
		vals = append(vals, tbl3dsRequest.PosEntryMode)
	}

	// PosConditionCode - 普通列
	generalColZeroVal = tbl3dsRequest.PosConditionCode == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "POS_CONDITION_CODE")
		vals = append(vals, tbl3dsRequest.PosConditionCode)
	}

	// PosPinCaptureCode - 普通列
	generalColZeroVal = tbl3dsRequest.PosPinCaptureCode == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "POS_PIN_CAPTURE_CODE")
		vals = append(vals, tbl3dsRequest.PosPinCaptureCode)
	}

	// AcquiringInstitution - 普通列
	generalColZeroVal = tbl3dsRequest.AcquiringInstitution == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ACQUIRING_INSTITUTION")
		vals = append(vals, tbl3dsRequest.AcquiringInstitution)
	}

	// RetrievalReferenceNumber - 索引列
	if !filterIndex {
		isZero := tbl3dsRequest.RetrievalReferenceNumber == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "RETRIEVAL_REFERENCE_NUMBER")
			vals = append(vals, tbl3dsRequest.RetrievalReferenceNumber)
		}
	}

	// TerminalId - 普通列
	generalColZeroVal = tbl3dsRequest.TerminalId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "TERMINAL_ID")
		vals = append(vals, tbl3dsRequest.TerminalId)
	}

	// MerchantId - 索引列
	if !filterIndex {
		isZero := tbl3dsRequest.MerchantId == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "MERCHANT_ID")
			vals = append(vals, tbl3dsRequest.MerchantId)
		}
	}

	// CardAcceptorLocation - 普通列
	generalColZeroVal = tbl3dsRequest.CardAcceptorLocation == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARD_ACCEPTOR_LOCATION")
		vals = append(vals, tbl3dsRequest.CardAcceptorLocation)
	}

	// OrderCurrency - 普通列
	generalColZeroVal = tbl3dsRequest.OrderCurrency == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ORDER_CURRENCY")
		vals = append(vals, tbl3dsRequest.OrderCurrency)
	}

	// TransactionCurrency - 普通列
	generalColZeroVal = tbl3dsRequest.TransactionCurrency == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "TRANSACTION_CURRENCY")
		vals = append(vals, tbl3dsRequest.TransactionCurrency)
	}

	// BillingCurrency - 普通列
	generalColZeroVal = tbl3dsRequest.BillingCurrency == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "BILLING_CURRENCY")
		vals = append(vals, tbl3dsRequest.BillingCurrency)
	}

	// AdditionalPosData - 普通列
	generalColZeroVal = tbl3dsRequest.AdditionalPosData == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ADDITIONAL_POS_DATA")
		vals = append(vals, tbl3dsRequest.AdditionalPosData)
	}

	// CardType - 普通列
	generalColZeroVal = tbl3dsRequest.CardType == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARD_TYPE")
		vals = append(vals, tbl3dsRequest.CardType)
	}

	// DccFlag - 普通列
	generalColZeroVal = tbl3dsRequest.DccFlag == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "DCC_FLAG")
		vals = append(vals, tbl3dsRequest.DccFlag)
	}

	// KeyDatetime - 普通列
	generalColZeroVal = tbl3dsRequest.KeyDatetime == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "KEY_DATETIME")
		vals = append(vals, tbl3dsRequest.KeyDatetime)
	}

	// DeviceType - 普通列
	generalColZeroVal = tbl3dsRequest.DeviceType == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "DEVICE_TYPE")
		vals = append(vals, tbl3dsRequest.DeviceType)
	}

	// InterfaceVersion - 普通列
	generalColZeroVal = tbl3dsRequest.InterfaceVersion == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "INTERFACE_VERSION")
		vals = append(vals, tbl3dsRequest.InterfaceVersion)
	}

	// Ip - 普通列
	generalColZeroVal = tbl3dsRequest.Ip == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "IP")
		vals = append(vals, tbl3dsRequest.Ip)
	}

	// RiskServiceFlag - 普通列
	generalColZeroVal = tbl3dsRequest.RiskServiceFlag == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "RISK_SERVICE_FLAG")
		vals = append(vals, tbl3dsRequest.RiskServiceFlag)
	}

	// PaymentType - 普通列
	generalColZeroVal = tbl3dsRequest.PaymentType == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "PAYMENT_TYPE")
		vals = append(vals, tbl3dsRequest.PaymentType)
	}

	// CardholderCountry - 普通列
	generalColZeroVal = tbl3dsRequest.CardholderCountry == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARDHOLDER_COUNTRY")
		vals = append(vals, tbl3dsRequest.CardholderCountry)
	}

	// CardholderAddress - 普通列
	generalColZeroVal = tbl3dsRequest.CardholderAddress == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARDHOLDER_ADDRESS")
		vals = append(vals, tbl3dsRequest.CardholderAddress)
	}

	// CardholderName - 普通列
	generalColZeroVal = tbl3dsRequest.CardholderName == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARDHOLDER_NAME")
		vals = append(vals, tbl3dsRequest.CardholderName)
	}

	// CardholderState - 普通列
	generalColZeroVal = tbl3dsRequest.CardholderState == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARDHOLDER_STATE")
		vals = append(vals, tbl3dsRequest.CardholderState)
	}

	// CardholderCity - 普通列
	generalColZeroVal = tbl3dsRequest.CardholderCity == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARDHOLDER_CITY")
		vals = append(vals, tbl3dsRequest.CardholderCity)
	}

	// CardholderZipCode - 普通列
	generalColZeroVal = tbl3dsRequest.CardholderZipCode == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARDHOLDER_ZIP_CODE")
		vals = append(vals, tbl3dsRequest.CardholderZipCode)
	}

	// CardholderPhone - 普通列
	generalColZeroVal = tbl3dsRequest.CardholderPhone == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARDHOLDER_PHONE")
		vals = append(vals, tbl3dsRequest.CardholderPhone)
	}

	// CardholderEmail - 普通列
	generalColZeroVal = tbl3dsRequest.CardholderEmail == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARDHOLDER_EMAIL")
		vals = append(vals, tbl3dsRequest.CardholderEmail)
	}

	// Reserved1 - 普通列
	generalColZeroVal = tbl3dsRequest.Reserved1 == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "RESERVED_1")
		vals = append(vals, tbl3dsRequest.Reserved1)
	}

	// Reserved2 - 普通列
	generalColZeroVal = tbl3dsRequest.Reserved2 == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "RESERVED_2")
		vals = append(vals, tbl3dsRequest.Reserved2)
	}

	// InsertTimestamp - 索引列
	if !filterIndex {
		isZero := tbl3dsRequest.InsertTimestamp.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "INSERT_TIMESTAMP")
			vals = append(vals, tbl3dsRequest.InsertTimestamp)
		}
	}

	// InsertUser - 普通列
	generalColZeroVal = tbl3dsRequest.InsertUser == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "INSERT_USER")
		vals = append(vals, tbl3dsRequest.InsertUser)
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (tbl3dsRequest *Tbl3dsRequest) ToString() string {
	if tbl3dsRequest == nil {
		return ""
	}
	return fmt.Sprintf("Tbl3dsRequest:(%+v)", *tbl3dsRequest)
}

// Tbl3dsRequestAllowUpdateCols 支持更新的列名列表
var Tbl3dsRequestAllowUpdateCols = []string{"CLUSTER_ID", "TRANSACTION_TYPE", "ORDER_ID", "GATEWAY_SERVICE_KEY", "GLOBAL_TRACE_NO", "PAN", "PROCESSING_CODE", "ORDER_AMOUNT", "TRANSACTION_AMOUNT", "BILLING_AMOUNT", "TRANSMISSION_DATETIME", "CONVERSION_RATE_BILLING", "STAN", "LOCAL_TIME", "LOCAL_DATE", "MCC", "ACQUIRING_INST_COUNTRY_CODE", "POS_ENTRY_MODE", "POS_CONDITION_CODE", "POS_PIN_CAPTURE_CODE", "ACQUIRING_INSTITUTION", "RETRIEVAL_REFERENCE_NUMBER", "TERMINAL_ID", "MERCHANT_ID", "CARD_ACCEPTOR_LOCATION", "ORDER_CURRENCY", "TRANSACTION_CURRENCY", "BILLING_CURRENCY", "ADDITIONAL_POS_DATA", "CARD_TYPE", "DCC_FLAG", "KEY_DATETIME", "DEVICE_TYPE", "INTERFACE_VERSION", "IP", "RISK_SERVICE_FLAG", "PAYMENT_TYPE", "CARDHOLDER_COUNTRY", "CARDHOLDER_ADDRESS", "CARDHOLDER_NAME", "CARDHOLDER_STATE", "CARDHOLDER_CITY", "CARDHOLDER_ZIP_CODE", "CARDHOLDER_PHONE", "CARDHOLDER_EMAIL", "RESERVED_1", "RESERVED_2"}

// Tbl3dsRequestIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var Tbl3dsRequestIndexLeadingCols = []string{"ID", "INSERT_TIMESTAMP", "ORDER_ID", "RETRIEVAL_REFERENCE_NUMBER"}



// Tbl3dsRequestXxxxxArg Xxxxx 查询参数
type Tbl3dsRequestXxxxxArg struct {
	FieldMask *conditonwhere.FieldMask
	RRN string
}

func (tbl3dsRequestXxxxxArg *Tbl3dsRequestXxxxxArg) WithRRN(RRN string) *Tbl3dsRequestXxxxxArg{
	tbl3dsRequestXxxxxArg.RRN = RRN
	tbl3dsRequestXxxxxArg.FieldMask.Set("RRN")
	return tbl3dsRequestXxxxxArg
} 

// ConvertToMap 将参数转换为map
func (tbl3dsRequestXxxxxArg *Tbl3dsRequestXxxxxArg) ConvertToMap() map[string]interface{} {
	if tbl3dsRequestXxxxxArg == nil {
		return nil
	}
	return map[string]interface{}{
		"RRN": tbl3dsRequestXxxxxArg.RRN,
	}
}



// WhereDataToYAMLCache WhereDataYAML缓存
var Tbl3dsRequestWhereDataToYAMLCache = map[string]string{
	"Xxxxx":`conditions:
- expr: RETRIEVAL_REFERENCE_NUMBER = @RRN
operator: AND
`,
}


var Tbl3dsRequestConditionMap = map[string]*conditonwhere.MaskWhereCondition{}

// 初始注册自定义函数的condition
func init() {
	for key, whereDataYaml := range Tbl3dsRequestWhereDataToYAMLCache {
		var newData map[interface{}]interface{}
		yaml.Unmarshal([]byte(whereDataYaml), &newData)
		 Tbl3dsRequestConditionMap[key] = conditonwhere.ParseWhereCondition(newData)
	}
}
