package model
import (
	"fmt"
	"time"
)
// TmEtcRelationship 表模型
// AUTOGENERATED: DO NOT EDIT
type TmEtcRelationship struct {
	Org string `gorm:"column:ORG;primaryKey;not null" json:"Org"`
	EtcCardNo string `gorm:"column:ETC_CARD_NO;primaryKey;not null" json:"EtcCardNo"`
	CardNo string `gorm:"column:CARD_NO" json:"CardNo"`
	CurrCd string `gorm:"column:CURR_CD" json:"CurrCd"`
	EtcRelationship string `gorm:"column:ETC_RELATIONSHIP" json:"EtcRelationship"`
	RelationshipBulidDate time.Time `gorm:"column:RELATIONSHIP_BULID_DATE" json:"RelationshipBulidDate"`
	RelationshipCancelDate time.Time `gorm:"column:RELATIONSHIP_CANCEL_DATE" json:"RelationshipCancelDate"`
	ReservedField1 string `gorm:"column:RESERVED_FIELD1" json:"ReservedField1"`
	ReservedField2 string `gorm:"column:RESERVED_FIELD2" json:"ReservedField2"`
	ReservedField3 string `gorm:"column:RESERVED_FIELD3" json:"ReservedField3"`
	JpaVersion int64 `gorm:"column:JPA_VERSION" json:"JpaVersion"`
	CreatedTime time.Time `gorm:"column:CREATED_TIME;AUTOCREATETIME" json:"CreatedTime"`
	LastModifiedTime time.Time `gorm:"column:LAST_MODIFIED_TIME;AUTOUPDATETIME" json:"LastModifiedTime"`
}

// TmEtcRelationshipPrimarkey 多主键结构体
type TmEtcRelationshipPrimarkey struct {
	Org string
	EtcCardNo string
}

// TableName 返回表名
func (tmEtcRelationship *TmEtcRelationship) TableName() string {
	return "tm_etc_relationship"
}

// Clone 克隆对象
func (tmEtcRelationship *TmEtcRelationship) Clone() *TmEtcRelationship {
	if tmEtcRelationship == nil {
		return nil
	}
	return &TmEtcRelationship{
		Org: tmEtcRelationship.Org,
		EtcCardNo: tmEtcRelationship.EtcCardNo,
		CardNo: tmEtcRelationship.CardNo,
		CurrCd: tmEtcRelationship.CurrCd,
		EtcRelationship: tmEtcRelationship.EtcRelationship,
		RelationshipBulidDate: tmEtcRelationship.RelationshipBulidDate,
		RelationshipCancelDate: tmEtcRelationship.RelationshipCancelDate,
		ReservedField1: tmEtcRelationship.ReservedField1,
		ReservedField2: tmEtcRelationship.ReservedField2,
		ReservedField3: tmEtcRelationship.ReservedField3,
		JpaVersion: tmEtcRelationship.JpaVersion,
		CreatedTime: tmEtcRelationship.CreatedTime,
		LastModifiedTime: tmEtcRelationship.LastModifiedTime,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (tmEtcRelationship *TmEtcRelationship) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if tmEtcRelationship == nil {
		return nil, nil, fmt.Errorf("tmEtcRelationship is nil")
	}

	var cols []string
	var vals []interface{}

 // generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false
	

	// Org - 主键，索引列
	if !filterPrimary {
		isZero := tmEtcRelationship.Org == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "ORG")
			vals = append(vals, tmEtcRelationship.Org)
		}
	}

	// EtcCardNo - 主键，索引列
	if !filterPrimary {
		isZero := tmEtcRelationship.EtcCardNo == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "ETC_CARD_NO")
			vals = append(vals, tmEtcRelationship.EtcCardNo)
		}
	}

	// CardNo - 普通列
	generalColZeroVal = tmEtcRelationship.CardNo == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CARD_NO")
		vals = append(vals, tmEtcRelationship.CardNo)
	}

	// CurrCd - 普通列
	generalColZeroVal = tmEtcRelationship.CurrCd == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "CURR_CD")
		vals = append(vals, tmEtcRelationship.CurrCd)
	}

	// EtcRelationship - 普通列
	generalColZeroVal = tmEtcRelationship.EtcRelationship == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "ETC_RELATIONSHIP")
		vals = append(vals, tmEtcRelationship.EtcRelationship)
	}

	// RelationshipBulidDate - 普通列
	generalColZeroVal = tmEtcRelationship.RelationshipBulidDate.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "RELATIONSHIP_BULID_DATE")
		vals = append(vals, tmEtcRelationship.RelationshipBulidDate)
	}

	// RelationshipCancelDate - 普通列
	generalColZeroVal = tmEtcRelationship.RelationshipCancelDate.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "RELATIONSHIP_CANCEL_DATE")
		vals = append(vals, tmEtcRelationship.RelationshipCancelDate)
	}

	// ReservedField1 - 普通列
	generalColZeroVal = tmEtcRelationship.ReservedField1 == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "RESERVED_FIELD1")
		vals = append(vals, tmEtcRelationship.ReservedField1)
	}

	// ReservedField2 - 普通列
	generalColZeroVal = tmEtcRelationship.ReservedField2 == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "RESERVED_FIELD2")
		vals = append(vals, tmEtcRelationship.ReservedField2)
	}

	// ReservedField3 - 普通列
	generalColZeroVal = tmEtcRelationship.ReservedField3 == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "RESERVED_FIELD3")
		vals = append(vals, tmEtcRelationship.ReservedField3)
	}

	// JpaVersion - 普通列
	generalColZeroVal = tmEtcRelationship.JpaVersion == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "JPA_VERSION")
		vals = append(vals, tmEtcRelationship.JpaVersion)
	}

	// CreatedTime - 特殊列，用于自动创建时间
	if !filterSpecial {
		isZero := tmEtcRelationship.CreatedTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "CREATED_TIME")
			vals = append(vals, tmEtcRelationship.CreatedTime)
		}
	}

	// LastModifiedTime - 特殊列，用于特殊用途
	if !filterSpecial {
		isZero := tmEtcRelationship.LastModifiedTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "LAST_MODIFIED_TIME")
			vals = append(vals, tmEtcRelationship.LastModifiedTime)
		}
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (tmEtcRelationship *TmEtcRelationship) ToString() string {
	if tmEtcRelationship == nil {
		return ""
	}
	return fmt.Sprintf("TmEtcRelationship:(%+v)", *tmEtcRelationship)
}

// TmEtcRelationshipAllowUpdateCols 支持更新的列名列表
var TmEtcRelationshipAllowUpdateCols = []string{"LAST_MODIFIED_TIME"}

// TmEtcRelationshipIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var TmEtcRelationshipIndexLeadingCols = []string{"ORG"}



