package model
import (
	"fmt"
	"time"
)
// TmNoPrimary 表模型
// AUTOGENERATED: DO NOT EDIT
type TmNoPrimary struct {
	TenantId int64 `gorm:"column:tenant_id" json:"TenantId"`
	StudentNo string `gorm:"column:student_no" json:"StudentNo"`
	Name string `gorm:"column:name;index:tm_teacher_Name_IDX,priority:1" json:"Name"`
	Address string `gorm:"column:address;index:tm_teacher_Name_IDX,priority:2" json:"Address"`
	Phone string `gorm:"column:phone;index:tm_teacher_phone_IDX,priority:1" json:"Phone"`
	ClassId string `gorm:"column:class_id;index:tm_teacher_classid_IDX,priority:1" json:"ClassId"`
	CardNo string `gorm:"column:card_no;index:tm_teacher_name_IDX,priority:1" json:"CardNo"`
	Score float64 `gorm:"column:score" json:"Score"`
	EnrollDate *time.Time `gorm:"column:enroll_date" json:"EnrollDate"`
	IsGraduate bool `gorm:"column:is_graduate" json:"IsGraduate"`
	JpaVersion int64 `gorm:"column:jpa_version" json:"JpaVersion"`
	CreateTime time.Time `gorm:"column:create_time;AUTOCREATETIME" json:"CreateTime"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;AUTOUPDATETIME" json:"LastUpdateTime"`
}

// TmNoPrimaryPrimarkey 多主键结构体
type TmNoPrimaryPrimarkey struct {

}

// TableName 返回表名
func (tmNoPrimary *TmNoPrimary) TableName() string {
	return "tm_no_primary"
}

// Clone 克隆对象
func (tmNoPrimary *TmNoPrimary) Clone() *TmNoPrimary {
	if tmNoPrimary == nil {
		return nil
	}
	return &TmNoPrimary{
		TenantId: tmNoPrimary.TenantId,
		StudentNo: tmNoPrimary.StudentNo,
		Name: tmNoPrimary.Name,
		Address: tmNoPrimary.Address,
		Phone: tmNoPrimary.Phone,
		ClassId: tmNoPrimary.ClassId,
		CardNo: tmNoPrimary.CardNo,
		Score: tmNoPrimary.Score,
		EnrollDate: tmNoPrimary.EnrollDate,
		IsGraduate: tmNoPrimary.IsGraduate,
		JpaVersion: tmNoPrimary.JpaVersion,
		CreateTime: tmNoPrimary.CreateTime,
		LastUpdateTime: tmNoPrimary.LastUpdateTime,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (tmNoPrimary *TmNoPrimary) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if tmNoPrimary == nil {
		return nil, nil, fmt.Errorf("tmNoPrimary is nil")
	}

	var cols []string
	var vals []interface{}

 // generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false
	

	// TenantId - 普通列
	generalColZeroVal = tmNoPrimary.TenantId == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "tenant_id")
		vals = append(vals, tmNoPrimary.TenantId)
	}

	// StudentNo - 普通列
	generalColZeroVal = tmNoPrimary.StudentNo == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "student_no")
		vals = append(vals, tmNoPrimary.StudentNo)
	}

	// Name - 索引列
	if !filterIndex {
		isZero := tmNoPrimary.Name == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "name")
			vals = append(vals, tmNoPrimary.Name)
		}
	}

	// Address - 索引列
	if !filterIndex {
		isZero := tmNoPrimary.Address == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "address")
			vals = append(vals, tmNoPrimary.Address)
		}
	}

	// Phone - 索引列
	if !filterIndex {
		isZero := tmNoPrimary.Phone == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "phone")
			vals = append(vals, tmNoPrimary.Phone)
		}
	}

	// ClassId - 索引列
	if !filterIndex {
		isZero := tmNoPrimary.ClassId == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "class_id")
			vals = append(vals, tmNoPrimary.ClassId)
		}
	}

	// CardNo - 索引列
	if !filterIndex {
		isZero := tmNoPrimary.CardNo == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "card_no")
			vals = append(vals, tmNoPrimary.CardNo)
		}
	}

	// Score - 普通列
	generalColZeroVal = tmNoPrimary.Score == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "score")
		vals = append(vals, tmNoPrimary.Score)
	}

	// EnrollDate - 普通列
	generalColZeroVal = tmNoPrimary.EnrollDate == nil
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "enroll_date")
		vals = append(vals, tmNoPrimary.EnrollDate)
	}

	// IsGraduate - 普通列
	generalColZeroVal = !tmNoPrimary.IsGraduate
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "is_graduate")
		vals = append(vals, tmNoPrimary.IsGraduate)
	}

	// JpaVersion - 特殊列，用于乐观锁
	if !filterSpecial {
		isZero := tmNoPrimary.JpaVersion == 0
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "jpa_version")
			vals = append(vals, tmNoPrimary.JpaVersion)
		}
	}

	// CreateTime - 特殊列，用于自动创建时间
	if !filterSpecial {
		isZero := tmNoPrimary.CreateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "create_time")
			vals = append(vals, tmNoPrimary.CreateTime)
		}
	}

	// LastUpdateTime - 特殊列，用于自动更新时间
	if !filterSpecial {
		isZero := tmNoPrimary.LastUpdateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "last_update_time")
			vals = append(vals, tmNoPrimary.LastUpdateTime)
		}
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (tmNoPrimary *TmNoPrimary) ToString() string {
	if tmNoPrimary == nil {
		return ""
	}
	return fmt.Sprintf("TmNoPrimary:(%+v)", *tmNoPrimary)
}

// TmNoPrimaryAllowUpdateCols 支持更新的列名列表
var TmNoPrimaryAllowUpdateCols = []string{"class_id", "card_no"}

// TmNoPrimaryIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var TmNoPrimaryIndexLeadingCols = []string{"card_no", "phone", "class_id", "name"}



