package model
import (
	"fmt"
	"github.com/shopspring/decimal"
	"time"
)
// TmNoIndex 表模型
// AUTOGENERATED: DO NOT EDIT
type TmNoIndex struct {
	TenantId int64 `gorm:"column:tenant_id;primaryKey;not null" json:"TenantId"`
	StudentNo string `gorm:"column:student_no;primaryKey;not null;size:20" json:"StudentNo"`
	Name string `gorm:"column:name;size:20" json:"Name"`
	Address string `gorm:"column:address;size:100" json:"Address"`
	Phone string `gorm:"column:phone;size:11" json:"Phone"`
	ClassId string `gorm:"column:class_id;size:2" json:"ClassId"`
	CardNo string `gorm:"column:card_no;size:20" json:"CardNo"`
	Score decimal.Decimal `gorm:"column:score;type:decimal(10,2);precision:10;scale:2" json:"Score"`
	EnrollDate *time.Time `gorm:"column:enroll_date" json:"EnrollDate"`
	IsGraduate bool `gorm:"column:is_graduate" json:"IsGraduate"`
	JpaVersion int64 `gorm:"column:jpa_version" json:"JpaVersion"`
	CreateTime time.Time `gorm:"column:create_time;AUTOCREATETIME" json:"CreateTime"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;AUTOUPDATETIME" json:"LastUpdateTime"`
}

// TmNoIndexPrimarkey 多主键结构体
type TmNoIndexPrimarkey struct {
	TenantId int64
	StudentNo string
}

// TableName 返回表名
func (tmNoIndex *TmNoIndex) TableName() string {
	return "tm_no_index"
}

// Clone 克隆对象
func (tmNoIndex *TmNoIndex) Clone() *TmNoIndex {
	if tmNoIndex == nil {
		return nil
	}
	return &TmNoIndex{
		TenantId: tmNoIndex.TenantId,
		StudentNo: tmNoIndex.StudentNo,
		Name: tmNoIndex.Name,
		Address: tmNoIndex.Address,
		Phone: tmNoIndex.Phone,
		ClassId: tmNoIndex.ClassId,
		CardNo: tmNoIndex.CardNo,
		Score: tmNoIndex.Score,
		EnrollDate: tmNoIndex.EnrollDate,
		IsGraduate: tmNoIndex.IsGraduate,
		JpaVersion: tmNoIndex.JpaVersion,
		CreateTime: tmNoIndex.CreateTime,
		LastUpdateTime: tmNoIndex.LastUpdateTime,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (tmNoIndex *TmNoIndex) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if tmNoIndex == nil {
		return nil, nil, fmt.Errorf("tmNoIndex is nil")
	}

	var cols []string
	var vals []interface{}

 // generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false
	

	// TenantId - 主键，索引列
	if !filterPrimary {
		isZero := tmNoIndex.TenantId == 0
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "tenant_id")
			vals = append(vals, tmNoIndex.TenantId)
		}
	}

	// StudentNo - 主键，索引列
	if !filterPrimary {
		isZero := tmNoIndex.StudentNo == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "student_no")
			vals = append(vals, tmNoIndex.StudentNo)
		}
	}

	// Name - 普通列
	generalColZeroVal = tmNoIndex.Name == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "name")
		vals = append(vals, tmNoIndex.Name)
	}

	// Address - 普通列
	generalColZeroVal = tmNoIndex.Address == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "address")
		vals = append(vals, tmNoIndex.Address)
	}

	// Phone - 普通列
	generalColZeroVal = tmNoIndex.Phone == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "phone")
		vals = append(vals, tmNoIndex.Phone)
	}

	// ClassId - 普通列
	generalColZeroVal = tmNoIndex.ClassId == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "class_id")
		vals = append(vals, tmNoIndex.ClassId)
	}

	// CardNo - 普通列
	generalColZeroVal = tmNoIndex.CardNo == ""
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "card_no")
		vals = append(vals, tmNoIndex.CardNo)
	}

	// Score - 普通列
	generalColZeroVal = tmNoIndex.Score.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "score")
		vals = append(vals, tmNoIndex.Score)
	}

	// EnrollDate - 普通列
	generalColZeroVal = tmNoIndex.EnrollDate == nil
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "enroll_date")
		vals = append(vals, tmNoIndex.EnrollDate)
	}

	// IsGraduate - 普通列
	generalColZeroVal = !tmNoIndex.IsGraduate
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "is_graduate")
		vals = append(vals, tmNoIndex.IsGraduate)
	}

	// JpaVersion - 特殊列，用于乐观锁
	if !filterSpecial {
		isZero := tmNoIndex.JpaVersion == 0
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "jpa_version")
			vals = append(vals, tmNoIndex.JpaVersion)
		}
	}

	// CreateTime - 特殊列，用于自动创建时间
	if !filterSpecial {
		isZero := tmNoIndex.CreateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "create_time")
			vals = append(vals, tmNoIndex.CreateTime)
		}
	}

	// LastUpdateTime - 特殊列，用于自动更新时间
	if !filterSpecial {
		isZero := tmNoIndex.LastUpdateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "last_update_time")
			vals = append(vals, tmNoIndex.LastUpdateTime)
		}
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (tmNoIndex *TmNoIndex) ToString() string {
	if tmNoIndex == nil {
		return ""
	}
	return fmt.Sprintf("TmNoIndex:(%+v)", *tmNoIndex)
}

// TmNoIndexAllowUpdateCols 支持更新的列名列表
var TmNoIndexAllowUpdateCols = []string{"class_id", "card_no"}

// TmNoIndexIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var TmNoIndexIndexLeadingCols = []string{"tenant_id"}



