package model
import (
	"fmt"
	db "github.com/aif-go/ag-core/contribute/agdb/gormdb"
	"github.com/aif-go/ag-core/contribute/agdb/conditonwhere"
	"gopkg.in/yaml.v2"
	"time"
)
// TmTeacher 表模型
// AUTOGENERATED: DO NOT EDIT
type TmTeacher struct {
	Id int64 `gorm:"column:id;primaryKey;not null" json:"Id"`
	Name string `gorm:"column:name;index:tm_teacher_Name_IDX,priority:1" json:"Name"`
	Address string `gorm:"column:address;index:tm_teacher_Name_IDX,priority:2" json:"Address"`
	Phone string `gorm:"column:phone;index:tm_teacher_phone_IDX,priority:1" json:"Phone"`
	ClassId string `gorm:"column:class_id;index:tm_teacher_classid_IDX,priority:1" json:"ClassId"`
	CardNo string `gorm:"column:card_no;index:tm_teacher_name_IDX,priority:1" json:"CardNo"`
	Salary float64 `gorm:"column:salary" json:"Salary"`
	JpaVersion int64 `gorm:"column:jpa_version" json:"JpaVersion"`
	CreateTime time.Time `gorm:"column:create_time;AUTOCREATETIME" json:"CreateTime"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;AUTOUPDATETIME" json:"LastUpdateTime"`
}

// TmTeacherPrimaryKey 单主键类型别名
type TmTeacherPrimaryKey int64

// TableName 返回表名
func (tmTeacher *TmTeacher) TableName() string {
	return "tm_teacher"
}

// Clone 克隆对象
func (tmTeacher *TmTeacher) Clone() *TmTeacher {
	if tmTeacher == nil {
		return nil
	}
	return &TmTeacher{
		Id: tmTeacher.Id,
		Name: tmTeacher.Name,
		Address: tmTeacher.Address,
		Phone: tmTeacher.Phone,
		ClassId: tmTeacher.ClassId,
		CardNo: tmTeacher.CardNo,
		Salary: tmTeacher.Salary,
		JpaVersion: tmTeacher.JpaVersion,
		CreateTime: tmTeacher.CreateTime,
		LastUpdateTime: tmTeacher.LastUpdateTime,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (tmTeacher *TmTeacher) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if tmTeacher == nil {
		return nil, nil, fmt.Errorf("tmTeacher is nil")
	}

	var cols []string
	var vals []interface{}

 // generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false
	

	// Id - 主键，索引列
	if !filterPrimary {
		isZero := tmTeacher.Id == 0
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "id")
			vals = append(vals, tmTeacher.Id)
		}
	}

	// Name - 索引列
	if !filterIndex {
		isZero := tmTeacher.Name == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "name")
			vals = append(vals, tmTeacher.Name)
		}
	}

	// Address - 索引列
	if !filterIndex {
		isZero := tmTeacher.Address == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "address")
			vals = append(vals, tmTeacher.Address)
		}
	}

	// Phone - 索引列
	if !filterIndex {
		isZero := tmTeacher.Phone == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "phone")
			vals = append(vals, tmTeacher.Phone)
		}
	}

	// ClassId - 索引列
	if !filterIndex {
		isZero := tmTeacher.ClassId == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "class_id")
			vals = append(vals, tmTeacher.ClassId)
		}
	}

	// CardNo - 索引列
	if !filterIndex {
		isZero := tmTeacher.CardNo == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "card_no")
			vals = append(vals, tmTeacher.CardNo)
		}
	}

	// Salary - 普通列
	generalColZeroVal = tmTeacher.Salary == 0
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "salary")
		vals = append(vals, tmTeacher.Salary)
	}

	// JpaVersion - 特殊列，用于乐观锁
	if !filterSpecial {
		isZero := tmTeacher.JpaVersion == 0
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "jpa_version")
			vals = append(vals, tmTeacher.JpaVersion)
		}
	}

	// CreateTime - 特殊列，用于自动创建时间
	if !filterSpecial {
		isZero := tmTeacher.CreateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "create_time")
			vals = append(vals, tmTeacher.CreateTime)
		}
	}

	// LastUpdateTime - 特殊列，用于自动更新时间
	if !filterSpecial {
		isZero := tmTeacher.LastUpdateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "last_update_time")
			vals = append(vals, tmTeacher.LastUpdateTime)
		}
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (tmTeacher *TmTeacher) ToString() string {
	if tmTeacher == nil {
		return ""
	}
	return fmt.Sprintf("TmTeacher:(%+v)", *tmTeacher)
}

// TmTeacherAllowUpdateCols 支持更新的列名列表
var TmTeacherAllowUpdateCols = []string{"class_id", "card_no"}

// TmTeacherIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var TmTeacherIndexLeadingCols = []string{"id", "class_id", "name", "card_no", "phone"}



// TmTeacherFindByPhoneArg FindByPhone 查询参数
type TmTeacherFindByPhoneArg struct {
	db.Page
	FieldMask *conditonwhere.FieldMask
	Phone string
}

func (tmTeacherFindByPhoneArg *TmTeacherFindByPhoneArg) WithPhone(Phone string) *TmTeacherFindByPhoneArg{
	tmTeacherFindByPhoneArg.Phone = Phone
	tmTeacherFindByPhoneArg.FieldMask.Set("Phone")
	return tmTeacherFindByPhoneArg
} 

// ConvertToMap 将参数转换为map
func (tmTeacherFindByPhoneArg *TmTeacherFindByPhoneArg) ConvertToMap() map[string]interface{} {
	if tmTeacherFindByPhoneArg == nil {
		return nil
	}
	return map[string]interface{}{
		"Page": tmTeacherFindByPhoneArg.Page,
		"Phone": tmTeacherFindByPhoneArg.Phone,
	}
}

// TmTeacherFindByPhonePageRes FindByPhone 分页查询结果
type TmTeacherFindByPhonePageRes struct {
	db.PageResult
	ResultList []*TmTeacher
}

// TmTeacherFindByNameNadAddressArg FindByNameNadAddress 查询参数
type TmTeacherFindByNameNadAddressArg struct {
	FieldMask *conditonwhere.FieldMask
	Name string
	Address string
}

func (tmTeacherFindByNameNadAddressArg *TmTeacherFindByNameNadAddressArg) WithName(Name string) *TmTeacherFindByNameNadAddressArg{
	tmTeacherFindByNameNadAddressArg.Name = Name
	tmTeacherFindByNameNadAddressArg.FieldMask.Set("Name")
	return tmTeacherFindByNameNadAddressArg
} 

func (tmTeacherFindByNameNadAddressArg *TmTeacherFindByNameNadAddressArg) WithAddress(Address string) *TmTeacherFindByNameNadAddressArg{
	tmTeacherFindByNameNadAddressArg.Address = Address
	tmTeacherFindByNameNadAddressArg.FieldMask.Set("Address")
	return tmTeacherFindByNameNadAddressArg
} 

// ConvertToMap 将参数转换为map
func (tmTeacherFindByNameNadAddressArg *TmTeacherFindByNameNadAddressArg) ConvertToMap() map[string]interface{} {
	if tmTeacherFindByNameNadAddressArg == nil {
		return nil
	}
	return map[string]interface{}{
		"Name": tmTeacherFindByNameNadAddressArg.Name,
		"Address": tmTeacherFindByNameNadAddressArg.Address,
	}
}

// TmTeacherFindByNameNadAddressRes FindByNameNadAddress 查询结果
type TmTeacherFindByNameNadAddressRes struct {
	Name string `gorm:"column:name" json:"Name"`
	Address string `gorm:"column:address" json:"Address"`
	Phone string `gorm:"column:phone" json:"Phone"`
	ClassId string `gorm:"column:class_id" json:"ClassId"`
}



// WhereDataToYAMLCache WhereDataYAML缓存
var TmTeacherWhereDataToYAMLCache = map[string]string{
	"FindByPhone":`conditions:
- expr: phone = @Phone
operator: AND
`,
	"FindByNameNadAddress":`conditions:
- expr: name like %@Name
- expr: address like %@Address%
operator: AND
`,
}


var TmTeacherConditionMap = map[string]*conditonwhere.MaskWhereCondition{}

// 初始注册自定义函数的condition
func init() {
	for key, whereDataYaml := range TmTeacherWhereDataToYAMLCache {
		var newData map[interface{}]interface{}
		yaml.Unmarshal([]byte(whereDataYaml), &newData)
		 TmTeacherConditionMap[key] = conditonwhere.ParseWhereCondition(newData)
	}
}
