package templates

var DaoTemplate = `// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT

package dao
import (
       "context"
       "{{.ModelName}}/repository/model"
       db "ag-core/contribute/agdb/gormdb"
{{- range .DaoImports}}
       "{{ .}}"
{{- end}}

    agdao "ag-core/contribute/agdb/agdao"
    "strings"
{{- if .NamingSqlMapEnable}}    
    "gorm.io/gorm"
{{- end}}    
)


{{- if .NamingSqlMapEnable}}
var {{.ObjectName}}NamingSqlMap = map[string]string{}
{{- end}}

// insert忽略空值时标记哪些字段需要排除在外
var exclude{{.ObjectName}}ZeroColNames = map[string]int {
{{- range .ColumnList}} 
{{- if or .AutoCreate .AutoUpdate .JPAVersion }}"{{.GoColName}}": 0,{{- end}} 
{{- end}}
}

type I{{.ObjectName}}Dao interface {
    InsertOne(ctx context.Context, arg *model.{{.ObjectName}}) (int64, error)
    InsertOneIgnorenNullCols(ctx context.Context, arg *model.{{.ObjectName}}) (int64, error)
    {{.PrimryRIndex.IndexName -}}
    (ctx context.Context, {{.PrimryRIndex.HashParamters}}) (*model.{{.ObjectName}}, error)
    UpdateByPrimaryKey(ctx context.Context, arg *model.{{.ObjectName}}) (int64, error)
    UpdateByPriIngoreNullCols(ctx context.Context, arg *model.{{.ObjectName}}) (int64, error)
    {{.PrimryDIndex.IndexName -}}
    (ctx context.Context, {{.PrimryDIndex.HashParamters}}) (int64, error)
    {{- range .GeneralIndexList}}
        FindBy{{ .MethodName }}(ctx context.Context, {{.HashParamters}}) ([]model.{{$.ObjectName}}, error)
    {{- end}}
    {{/* 索引操作 */}}
    {{- range .UniqueIndexList}}
        FindBy{{ .MethodName }}(ctx context.Context, {{.HashParamters}}) (*model.{{$.ObjectName}}, error)
        UpdateBy{{ .MethodName }}(ctx context.Context, {{.HashParamters}}, arg *model.{{$.ObjectName}})(int64, error)
        DeleteBy{{ .MethodName }}(ctx context.Context, {{.HashParamters}})(int64, error)
    {{- end}}

    {{- range .RNamingSqlList}}
        {{if .PageCountSql}}
            {{.MethodName}}(ctx context.Context, arg *model.{{$.ObjectName}}{{.MethodName}}Arg) (*model.{{$.ObjectName}}{{.MethodResName}}, error)
        {{else}}
            {{if .SelectAllCol}}
                // 查询全部列
                {{.MethodName}}(ctx context.Context, arg *model.{{$.ObjectName}}{{.MethodName}}Arg) ([]*model.{{$.ObjectName}}, error)
            {{else}}
                // 查询指定列
                {{.MethodName}}(ctx context.Context, arg *model.{{$.ObjectName}}{{.MethodName}}Arg) ([]*model.{{$.ObjectName}}{{.MethodResName}}, error)
            {{- end}}
        {{- end}}
    {{- end}}

    {{- range .CUDNamingSqlList}}
        {{.MethodName}}(ctx context.Context, arg *model.{{$.ObjectName}}{{.MethodName}}Arg) (int64, error)
    {{- end}}
}


type {{.ObjectName}}Dao struct {
    *db.Repository
    info agdao.TableInfo
    baseDao agdao.BaseDao
}

// New{{.ObjectName}}Dao get dao instance
func New{{.ObjectName}}Dao(repository *db.Repository, baseDao agdao.BaseDao) I{{.ObjectName}}Dao {
{{- if .NamingSqlMapEnable}}
    Init{{.ObjectName}}NamingSql()
{{- end}}    
    return &{{.ObjectName}}Dao{
        Repository: repository,
        baseDao: baseDao,
        info: agdao.TableInfo{
            TableName: "{{.TableName}}",
        },
    }
}

// InsertOne 插入数据
func (dao *{{.ObjectName}}Dao) InsertOne(ctx context.Context, arg *model.{{.ObjectName}})(int64, error) {
	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
    result:=db.Create(arg)
    return result.RowsAffected, result.Error
}

// InsertOneIgnorenNullCols 插入数据时，自动剔除零值的列
func (dao *{{.ObjectName}}Dao) InsertOneIgnorenNullCols(ctx context.Context, arg *model.{{.ObjectName}})(int64, error) {
    insertIgnoreZeroValSlice := db.CollectZeroValWithOmitEmpty(arg, exclude{{.ObjectName}}ZeroColNames)
	db, err := dao.newDB(ctx)
	if err != nil {
		return 0, err
	}
    result:=db.Omit(insertIgnoreZeroValSlice...).Create(arg)
    return result.RowsAffected, result.Error
}

func (dao *{{.ObjectName}}Dao) {{.PrimryRIndex.IndexName}}(ctx context.Context, {{.PrimryRIndex.HashParamters}}) (*model.{{.ObjectName}}, error) {
    findRes :=&model.{{.ObjectName}}{}
    db, err := dao.newDB(ctx)
	if err != nil {
		return nil, err
	}
    {{- range .PrimryRIndex.BindParamList}}
        db = db.Where("{{.DbColName}}",{{.GoColName}})
    {{- end}}
    result := db.Find(findRes)
    return findRes, result.Error
}


// UpdateByPrimaryKey 根据主键更新，该操作只适合从数据库查询原实体修改值之后使用
func (dao *{{.ObjectName}}Dao) UpdateByPrimaryKey(ctx context.Context, arg *model.{{.ObjectName}})(int64, error){
      
    db, err:= dao.newDB(ctx)
    if err!= nil {
		return 0, err
	}
    result:=db.Save(arg)
    return result.RowsAffected, result.Error
}


// UpdateByPriIngoreNullCols 根据主键更新，自动剔除参数中的零值列
func (dao *{{.ObjectName}}Dao) UpdateByPriIngoreNullCols(ctx context.Context, arg *model.{{.ObjectName}})(int64, error){
      
    db, err := dao.newDB(ctx)
    if err != nil {
		return 0, err
	}
    result:=db.Model(arg).Updates(arg)
    return result.RowsAffected, result.Error
}

func (dao *{{.ObjectName}}Dao) {{.PrimryDIndex.IndexName}}(ctx context.Context, {{.PrimryDIndex.HashParamters}})(int64, error){
      
    db, err:= dao.newDB(ctx)
    if err!= nil {
		return 0, err
	}
    result:=db{{- range .PrimryDIndex.BindParamList}}.Where("{{.DbColName}}",{{.GoColName}}){{- end}}.Delete(&model.{{.ObjectName}}{})
    return result.RowsAffected, result.Error
}

{{- range .GeneralIndexList}}

func (dao *{{$.ObjectName}}Dao) FindBy{{ .MethodName }}(ctx context.Context, {{.HashParamters}})([]model.{{$.ObjectName}}, error){
   var list []model.{{$.ObjectName}}
   db, err := dao.newDB(ctx)
   if err != nil {
		return nil, err
	}
   result:=db{{- range .BindParamList}}.Where("{{.DbColName}}", {{ .GoColName }}){{- end}}.Find(&list)
   return list, result.Error
} 
{{- end}}



{{- range .UniqueIndexList}}

func (dao *{{$.ObjectName}}Dao) FindBy{{ .MethodName }}(ctx context.Context, {{.HashParamters}})(*model.{{$.ObjectName}}, error){
   findRes :=&model.{{$.ObjectName}}{}
   db, err := dao.newDB(ctx)
   if err != nil {
		return nil, err
	}
   result:=db{{- range .BindParamList}}.Where("{{.DbColName}}",{{.GoColName }}){{- end}}.Find(findRes)
   return findRes, result.Error
} 

// UpdateBy{{ .MethodName }} 根据唯一索引更新数据,自动剔除零值的列
func (dao *{{$.ObjectName}}Dao) UpdateBy{{ .MethodName }} (ctx context.Context, {{.HashParamters}}, arg *model.{{$.ObjectName}})(int64, error){
   db, err := dao.newDB(ctx)
   if err != nil {
		return 0, err
	}
   result:=db.Model(&model.{{$.ObjectName}}{}){{- range .BindParamList}}.Where("{{.DbColName}}", {{ .GoColName }}){{- end}}.Updates(arg)
   return result.RowsAffected, result.Error
} 

// DeleteBy{{ .MethodName }} 根据唯一索引作为条件,删除满足条件的数据
func (dao *{{$.ObjectName}}Dao)  DeleteBy{{ .MethodName }}(ctx context.Context, {{.HashParamters}})(int64, error) {
   db, err := dao.newDB(ctx)
   if err != nil {
		return 0, err
	}
   result:=db{{- range .BindParamList}}.Where("{{.DbColName}}", {{ .GoColName }}){{- end}}.Delete(&model.{{$.ObjectName}}{})
   return result.RowsAffected, result.Error
}

{{- end}}


{{- range .RNamingSqlList}}
{{if .PageCountSql}}
// {{.MethodName}}分页查询
func (dao *{{$.ObjectName}}Dao) {{.MethodName}} (ctx context.Context, arg *model.{{$.ObjectName}}{{.MethodName}}Arg) (*model.{{$.ObjectName}}{{.MethodResName}}, error) {
   {{if .SelectAllCol}}
   var list []*model.{{$.ObjectName}}
   {{else}}
   var list []*model.{{$.ObjectName}}{{.MethodName}}  
   {{end}}
   sqlName:= {{$.ObjectName}}NamingSqlMap[dao.DbType+"_{{$.ObjectName}}_{{.MethodName}}"]
   if sqlName == "" {
      return nil, errors.New("不支持的db类型")
   }

   // 先查询总数
   countSql:={{$.ObjectName}}NamingSqlMap[dao.DbType+"_{{$.ObjectName}}_{{.MethodName}}_Count"]
   if countSql == "" {
      return nil, errors.New("不支持的db类型")
   }
   newTableName := dao.getApplyInfo(ctx).TableName
   if newTableName != "" {
		enity := &model.{{$.ObjectName}}{}
        sqlName = strings.ReplaceAll(sqlName, enity.TableName(), newTableName)
        countSql = strings.ReplaceAll(countSql, enity.TableName(), newTableName)
    }      
   var count int64
 {{- if .ToMap}}
   paraterMap:=arg.ToMap()
   countResult:=dao.DB(ctx).Raw(countSql, paraterMap).Scan(&count)
{{- else }}
   countResult:=dao.DB(ctx).Raw(countSql, arg).Scan(&count)    
{{- end}}  
   if countResult.Error!= nil {
      return nil, countResult.Error
   }
   startRecord,endRecord,totalPage:= db.CalcPageStartRecord(arg.PageNum, arg.PageSize, count, dao.DbType)
   res:=&model.{{$.ObjectName}}{{.MethodResName}}{
      PageNum: arg.PageNum,
      PageSize: arg.PageSize,
      TotalPage: totalPage,
      TotalCount: count,
      DataRes: list,
   }
   if count == 0 {
      return res, nil
   }
   if startRecord == 0 && endRecord == 0 {
      return res, nil
   }
{{- if .ToMap}}
   result:=dao.DB(ctx).Raw(sqlName, paraterMap).Find(&list)
{{- else }}
   result:=dao.DB(ctx).Raw(sqlName, arg).Find(&list)    
{{- end}}   
   res.DataRes=list
   return res, result.Error
}
{{else}}
{{if .SelectAllCol}}
// 查询全部列
func (dao *{{$.ObjectName}}Dao) {{.MethodName}} (ctx context.Context, arg *model.{{$.ObjectName}}{{.MethodName}}Arg) ([]*model.{{$.ObjectName}}, error) {  
   var list []*model.{{$.ObjectName}}
{{else}}
// 查询全部列
func (dao *{{$.ObjectName}}Dao) {{.MethodName}} (ctx context.Context, arg *model.{{$.ObjectName}}{{.MethodName}}Arg) ([]*model.{{$.ObjectName}}{{.MethodResName}}, error) {  
   var list []*model.{{$.ObjectName}}{{.MethodResName}}
{{end}}   
   sqlName:= {{$.ObjectName}}NamingSqlMap[dao.DbType+"_{{$.ObjectName}}_{{.MethodName}}"]
   if sqlName == "" {
      return nil, errors.New("不支持的db类型")
   }
   newTableName := dao.getApplyInfo(ctx).TableName
   if newTableName != "" {
		enity := &model.{{$.ObjectName}}{}
        sqlName = strings.ReplaceAll(sqlName, enity.TableName(), newTableName)
    }
{{- if .ToMap}}
   paraterMap:=arg.ToMap()
   result:=dao.DB(ctx).Raw(sqlName, paraterMap).Find(&list)
{{- else }}
   result:=dao.DB(ctx).Raw(sqlName, arg).Find(&list)    
{{- end}}   
   return list, result.Error
}
{{- end}}
{{- end}}



{{- range .CUDNamingSqlList}}
func (dao *{{$.ObjectName}}Dao) {{.MethodName}} (ctx context.Context, arg *model.{{$.ObjectName}}{{.MethodName}}Arg) (int64, error) {
      //sqlName:={{$.DbType}}_{{$.ObjectName}}_{{.MethodName}}
      sqlName:={{$.ObjectName}}NamingSqlMap[dao.DbType+"_{{$.ObjectName}}_{{.MethodName}}"]
      if sqlName == "" {
         return 0, errors.New("不支持的db类型")
      }
      db:= dao.newDB(ctx)
      {{- if .ToMap}}
      paraterMap:=arg.ToMap()
      result:=dao.DB(ctx).Exec(sqlName, paraterMap)
      {{- else }}
      result:=dao.DB(ctx).Exec(sqlName, arg)
      {{- end}}  

      return result.RowsAffected, result.Error
}

{{- end}}

func (dao *{{.ObjectName}}Dao) getInfo() agdao.TableInfo {
	return dao.info
}

func (dao *{{.ObjectName}}Dao) getApplyInfo(ctx context.Context) agdao.TableInfo {
    info := dao.getInfo() // 获取info副本
    dao.baseDao.ApplyTbInfoOpts(ctx, &info) // 对副本info进行增强
    return info
}

// newDB 创建一个新的DB实例，应用增强后的TableInfo
func (dao *{{.ObjectName}}Dao) newDB(ctx context.Context) (*gorm.DB, error) {
	db := dao.DB(ctx)

    info := dao.getApplyInfo(ctx)

    tbname := info.TableName
    if tbname == "" {
        return nil, errors.New("表名不能为空")
    }
	db = db.Table(tbname)
    return db, nil
}
`
