package templates

var EntityTemplate = `
// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT
// Code generated by aic-generate, DO NOT EDIT

package model
import (
	"fmt"
{{- range .Imports}}
	"{{ .}}"
{{- end}}
)

// {{.ObjectName}} mapped from table {{.TableName}}
type {{.ObjectName}} struct {
   {{- range .TableModelList}}
   {{.GoColName}}  {{.GoType}} ` + "`" + "{{unescaped .GoTag}}" + "`" + `
   {{- end}}
}

{{- range .RNamingSqlList }}
type {{$.ObjectName}}{{.MethodName}}Arg struct {
   {{- range .BindParam }}
   {{.GoColName}}  {{.GoType}}
   {{end}}
   {{- if .PageCountSql -}}
   PageNum int64 ` + "`" + `json:"pageNum"` + "`" + `
   PageSize int64 ` + "`" + `json:"pageSize"` + "`" + `
   {{- end}}
}

{{- if .ToMap }}
// ToMap convert entity to map
func (owner *{{$.ObjectName}}{{.MethodName}}Arg) ToMap() map[string]interface{} {
   if owner == nil{
      return nil
   }
   m := map[string]interface{} {
      {{- range .BindParam }}
       "{{.GoColName}}": owner.{{.GoColName}},
      {{- end }}
      {{- if .PageCountSql -}}
        PageNum : owner.PageNum,
        PageSize : owner.PageSize,
      {{- end }}
   }
   return m
}
{{- end}}   
{{- end}}

// 指定列查询返回实体定义
{{- range .RNamingSqlList }}
{{- if .GenerateBol}}
{{- if .PageCountSql}}
type {{$.ObjectName}}{{.MethodName}}Res struct {
   {{- if .SelectAllCol}}
   DataRes []*{{$.ObjectName}}
   {{else}}
   // 查询指定列
   DataRes []*{{$.ObjectName}}{{.MethodName}}
   {{end}}
   PageNum int64 ` + "`" + `json:"pageNum"` + "`" + `
   PageSize int64 ` + "`" + `json:"pageSize"` + "`" + `
   TotalPage int64 ` + "`" + `json:"totalPage"` + "`" + `
   TotalCount int64 ` + "`" + `json:"TotalCount"` + "`" + `

}
// 指定列查询返回实体定义
{{- if not .SelectAllCol}}
type {{$.ObjectName}}{{.MethodName}} struct {
   {{- range .SelectColumns}}
   {{.Alias}}  {{.GoType}} ` + "`" + "{{unescaped .Tag}}" + "`" + `  
   {{- end}}
}
{{- end}}
{{else}}
{{ if not .SelectAllCol}}
type {{$.ObjectName}}{{.MethodName}}Res struct {
   {{- range .SelectColumns }}
   {{.Alias}}  {{.GoType}} ` + "`" + "{{unescaped .Tag}}" + "`" + `  
   {{- end }}
}
{{- end}}
{{- end}}
{{- end}}
{{- end}}

{{- range .CUDNamingSqlList}}
type {{$.ObjectName}}{{.MethodName}}Arg struct {
   {{- range .BindParam}}
   {{.GoColName}}  {{.GoType}}
   {{- end}}
}
{{- end}}

// TableName {{.TableName}} table name
func (*{{.ObjectName}}) TableName() string {
   return "{{.TableName}}"
}


func (owner *{{.ObjectName}}) Clone() *{{.ObjectName}} {
   if owner == nil{
      return nil
   }
   return &{{.ObjectName}}{
   {{- range .TableModelList}}
      {{printf "%-10s%-8s%s" .GoColName ": owner." .GoColName}},
   {{- end}}
   }
}

func (owner *{{.ObjectName}}) ToString() string {
    if owner == nil{
      return "<nil>"
    }
    return fmt.Sprintf("{{.ObjectName}}:(%+v)", *owner)
}
`
