package generator

// Tpl_version 版本信息模板(通用模板)
var Tpl_version string = `
// Code generated by {{.PluginName}}. DO NOT EDIT!!!
// Code generated by {{.PluginName}}. DO NOT EDIT!!!
// Code generated by {{.PluginName}}. DO NOT EDIT!!!
//
// GenScope: {{.GenScope}}
{{- /* // Generate time: {{DateTimeNow}} */}}
{{- /* .Versions可能为空指针, 不为空且长度大于0 */}}
{{- if .Versions}}
	{{- /* .Versions长度大于0 */}}
	{{- if gt (len .Versions) 0}}
		// Versions:
		{{- range $name, $version := .Versions}}
		//   - {{$name}}: {{$version}}
		{{- end}}
	{{- end}}
{{- end}}
{{- if .Source}}
	{{- if gt (len .Source) 0}}
		// Source: 
		{{- range $source := .Source}}
		//   - {{$source}}
		{{- end}}
	{{- end}}
{{- end}}
`

// Tpl_import 导入模板(通用模板)
var Tpl_import string = `
{{- if .Imports}}
	{{- if gt (len .Imports) 0}}
		import (
			{{- range $path, $aliases := .Imports}}
				{{- if not $aliases}}
					"{{$path}}"
				{{- else}}
					{{- range $alias, $is := $aliases}}
						{{$alias}} "{{$path}}"
					{{- end}}
				{{- end}}
			{{- end}}
		)
	{{- end}}
{{- end}}
`

var Tpl_pkg string = `
package {{ToLower .GenPkgRefName}}

`
