package model

import (
	"fmt"
	"strings"

	"ag-core/tool/cmd/new-gen-db/table"
)

// hasWhereDataToYAMLCache 检查是否有 WhereDataToYAMLCache 需要生成
func hasWhereDataToYAMLCache(tableData *table.TableData) bool {
	if len(tableData.SelfQueries) == 0 {
		return false
	}
	for _, query := range tableData.SelfQueries {
		if query.WhereDataYaml != "" {
			return true
		}
	}
	return false
}

// generateImports 生成导入语句
func generateImports(tableData *table.TableData) string {
	var imports []string

	// 基础导入
	imports = append(imports, "\"fmt\"")

	// 根据需要添加导入
	if tableData.HasPage {
		imports = append(imports, `db "ag-core/contribute/agdb/gormdb"`)
	}
	if tableData.HasSelfQuery {
		imports = append(imports, `"ag-core/contribute/agdb/conditonwhere"`)
	}

	// 如果有 WhereDataToYAMLCache，需要导入 yaml 包
	if hasWhereDataToYAMLCache(tableData) {
		imports = append(imports, `"gopkg.in/yaml.v2"`)
	}

	// 添加自定义导入包
	if tableData.ModelTemplateData != nil && len(tableData.ModelTemplateData.ImportPackages) > 0 {
		for _, pkg := range tableData.ModelTemplateData.ImportPackages {
			if pkg != "fmt" { // 避免重复
				imports = append(imports, fmt.Sprintf("\"%s\"", pkg))
			}
		}
	}

	if len(imports) == 0 {
		return ""
	}

	return "import (\n\t" + strings.Join(imports, "\n\t") + "\n)"
}

// generateStruct 生成主结构体
func generateStruct(tableData *table.TableData) string {
	structName := tableData.StructName
	var fields []string

	for _, col := range tableData.Columns {
		fields = append(fields, fmt.Sprintf("\t%s %s `gorm:\"%s\" json:\"%s\"`",
			col.JsonTag, col.GoType, col.GormTag, col.JsonTag))
	}

	return fmt.Sprintf(`// %s 表模型
// AUTOGENERATED: DO NOT EDIT
type %s struct {
%s
}`, structName, structName, strings.Join(fields, "\n"))
}

// generatePrimaryKeyType 生成主键类型定义
func generatePrimaryKeyType(tableData *table.TableData) string {
	structName := tableData.StructName

	if len(tableData.PrimaryKeys) == 1 {
		// 单主键，使用类型别名
		for _, col := range tableData.Columns {
			if col.Name == tableData.PrimaryKeys[0] {
				return fmt.Sprintf(`// %sPrimaryKey 单主键类型别名
type %sPrimaryKey %s`, structName, structName, col.GoType)
			}
		}
	}

	// 多主键，使用结构体
	var fields []string
	for _, pk := range tableData.PrimaryKeys {
		for _, col := range tableData.Columns {
			if col.Name == pk {
				fields = append(fields, fmt.Sprintf("\t%s %s", col.JsonTag, col.GoType))
				break
			}
		}
	}

	return fmt.Sprintf(`// %sPrimarkey 多主键结构体
type %sPrimarkey struct {
%s
}`, structName, structName, strings.Join(fields, "\n"))
}

// generateTableNameMethod 生成TableName方法
func generateTableNameMethod(tableData *table.TableData) string {
	structName := tableData.StructName
	lowerStructName := strings.ToLower(string(structName[0])) + structName[1:]

	return fmt.Sprintf(`// TableName 返回表名
func (%s *%s) TableName() string {
	return "%s"
}`, lowerStructName, structName, tableData.TableName)
}

// generateCloneMethod 生成Clone方法
func generateCloneMethod(tableData *table.TableData) string {
	structName := tableData.StructName
	lowerStructName := strings.ToLower(string(structName[0])) + structName[1:]

	var fields []string
	for _, col := range tableData.Columns {
		fields = append(fields, fmt.Sprintf("\t\t%s: %s.%s,", col.JsonTag, lowerStructName, col.JsonTag))
	}

	return fmt.Sprintf(`// Clone 克隆对象
func (%s *%s) Clone() *%s {
	if %s == nil {
		return nil
	}
	return &%s{
%s
	}
}`, lowerStructName, structName, structName, lowerStructName, structName, strings.Join(fields, "\n"))
}

// generateToStringMethod 生成ToString方法
func generateToStringMethod(tableData *table.TableData) string {
	structName := tableData.StructName
	lowerStructName := strings.ToLower(string(structName[0])) + structName[1:]

	return fmt.Sprintf(`// ToString 转换为字符串
func (%s *%s) ToString() string {
	if %s == nil {
		return ""
	}
	return fmt.Sprintf("%s:(%%+v)", *%s)
}`, lowerStructName, structName, lowerStructName, structName, lowerStructName)
}

// generateAllowUpdateCols 生成AllowUpdateCols变量
func generateAllowUpdateCols(tableData *table.TableData) string {
	structName := tableData.StructName

	var cols []string
	for i, col := range tableData.AllowUpdateCols {
		if i > 0 {
			cols = append(cols, fmt.Sprintf(", \"%s\"", col))
		} else {
			cols = append(cols, fmt.Sprintf("\"%s\"", col))
		}
	}

	return fmt.Sprintf(`// %sAllowUpdateCols 支持更新的列名列表
var %sAllowUpdateCols = []string{%s}`, structName, structName, strings.Join(cols, ""))
}

// generateIndexLeadingCols 生成IndexLeadingCols变量
func generateIndexLeadingCols(tableData *table.TableData) string {
	structName := tableData.StructName
	
	var cols []string
	// 优先使用主键的第一列
	if len(tableData.PrimaryKeys) > 0 {
		cols = append(cols, fmt.Sprintf("\"%s\"", tableData.PrimaryKeys[0]))
	} 
	// 处理索引的引导列
	for _, index := range tableData.Indexes {
		if len(index.Columns) > 0 {
			cols = append(cols, fmt.Sprintf("\"%s\"", index.Columns[0]))
		}
	}
	if len(cols) == 0 {
		return ""
	}
	
	return fmt.Sprintf(`// %sIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var %sIndexLeadingCols = []string{%s}`, structName, structName, strings.Join(cols, ", "))
}

// // generateColumnStruct 生成Column结构体
// func generateColumnStruct(tableData *table.TableData) string {
// 	structName := tableData.StructName

// 	// 示例字段，实际应该根据需要生成
// 	return fmt.Sprintf(`// %sColumn 表列模型
// type %sColumn struct {
// 	Name    string
// 	Address string
// 	Phone   string
// 	ClassId string
// 	CardNo  string
// }`, structName, structName)
// }

// generateQueryArgStruct 生成查询参数结构体
func generateQueryArgStruct(tableData *table.TableData, query table.QueryData) string {
	structName := tableData.StructName
	queryName := query.Name

	var fields []string

	if query.HasPage {
		fields = append(fields, "\tdb.Page")
		fields = append(fields, "\tFieldMask *conditonwhere.FieldMask")
	} else {
		fields = append(fields, "\tFieldMask *conditonwhere.FieldMask")
	}

	for _, wc := range query.WhereColFields {
		for _, col := range tableData.Columns {
			if col.Name == wc.ColName {
				if wc.IsSlice {
					fields = append(fields, fmt.Sprintf("\t%s []%s", wc.FieldName, col.GoType))
				} else {
					fields = append(fields, fmt.Sprintf("\t%s %s", wc.FieldName, col.GoType))
				}
				break
			}
		}
	}

	return fmt.Sprintf(`// %s%sArg %s 查询参数
type %s%sArg struct {
%s
}`, structName, queryName, queryName, structName, queryName, strings.Join(fields, "\n"))
}

// generateWithMethods 生成With方法
func generateWithMethods(tableData *table.TableData, query table.QueryData) string {
	structName := tableData.StructName
	queryName := query.Name
	lowerStructName := strings.ToLower(string(structName[0])) + structName[1:]

	var methods []string

	for _, wc := range query.WhereColFields {
		for _, col := range tableData.Columns {
			if col.Name == wc.ColName {
				methods = append(methods, fmt.Sprintf(`func (%s%sArg *%s%sArg) With%s(%s %s) *%s%sArg{
	%s%sArg.%s = %s
	%s%sArg.FieldMask.Set("%s")
	return %s%sArg
} `, lowerStructName, queryName, structName, queryName, wc.FieldName, wc.FieldName, col.GoType,structName,queryName,
					lowerStructName, queryName, wc.FieldName, wc.FieldName, lowerStructName, queryName,wc.FieldName,lowerStructName, queryName))
				break
			}
		}
	}

	return strings.Join(methods, "\n\n")
}

// generateConvertToMapMethod 生成ConvertToMap方法
func generateConvertToMapMethod(tableData *table.TableData, query table.QueryData) string {
	structName := tableData.StructName
	queryName := query.Name
	lowerStructName := strings.ToLower(string(structName[0])) + structName[1:]

	var fields []string

	if query.HasPage {
		fields = append(fields, "\t\t\"Page\": " + lowerStructName + queryName + "Arg.Page,")
	}

	for _, wc := range query.WhereColFields {
		fields = append(fields, fmt.Sprintf("\t\t\"%s\": %s%sArg.%s,", wc.FieldName, lowerStructName, queryName, wc.FieldName))
	}

	return fmt.Sprintf(`// ConvertToMap 将参数转换为map
func (%s%sArg *%s%sArg) ConvertToMap() map[string]interface{} {
	if %s%sArg == nil {
		return nil
	}
	return map[string]interface{}{
%s
	}
}`, lowerStructName, queryName, structName, queryName, lowerStructName, queryName, strings.Join(fields, "\n"))
}

// generateQueryResStruct 生成查询结果结构体
func generateQueryResStruct(tableData *table.TableData, query table.QueryData) string {
	structName := tableData.StructName
	queryName := query.Name

	if query.SelectFields == "*" {
		// 使用主结构体
		return ""
	}

	var fields []string
	for _, col := range tableData.Columns {
		if contains(query.Fields, col.Name) {
			fields = append(fields, fmt.Sprintf("\t%s %s `gorm:\"column:%s\" json:\"%s\"`",
				col.JsonTag, col.GoType, col.Name, col.JsonTag))
		}
	}

	return fmt.Sprintf(`// %s%sRes %s 查询结果
type %s%sRes struct {
%s
}`, structName, queryName, queryName, structName, queryName, strings.Join(fields, "\n"))
}

// generatePageResStruct 生成分页结果结构体
func generatePageResStruct(tableData *table.TableData, query table.QueryData) string {
	structName := tableData.StructName
	queryName := query.Name

	var resultType string
	if query.SelectFields == "*" {
		resultType = structName
	} else {
		resultType = structName + queryName + "Res"
	}

	return fmt.Sprintf(`// %s%sPageRes %s 分页查询结果
type %s%sPageRes struct {
	db.PageResult
	ResultList []*%s
}`, structName, queryName, queryName, structName, queryName, resultType)
}

// generateQueryCode 生成自定义查询代码
func generateQueryCode(tableData *table.TableData) string {
	if len(tableData.SelfQueries) == 0 {
		return ""
	}

	var code strings.Builder

	for _, query := range tableData.SelfQueries {
		// 生成Arg结构体
		code.WriteString(generateQueryArgStruct(tableData, query))
		code.WriteString("\n\n")

		// 生成With方法
		code.WriteString(generateWithMethods(tableData, query))
		code.WriteString("\n\n")

		// 生成ConvertToMap方法
		code.WriteString(generateConvertToMapMethod(tableData, query))
		code.WriteString("\n\n")

		// 生成Res结构体（如果不是全表查询）
		if query.SelectFields != "*" {
			code.WriteString(generateQueryResStruct(tableData, query))
			code.WriteString("\n\n")
		}

		// 生成分页结果结构体（如果需要分页）
		if query.HasPage {
			code.WriteString(generatePageResStruct(tableData, query))
			code.WriteString("\n\n")
		}
	}

	return code.String()
}

// contains 检查字符串是否在切片中
func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}

// generateWhereDataToYAMLCache 生成WhereDataToYAMLCache map
func generateWhereDataToYAMLCache(tableData *table.TableData) string {
	if len(tableData.SelfQueries) == 0 {
		return ""
	}

	// structName := tableData.StructName
	var entries []string

	for _, query := range tableData.SelfQueries {
		if query.WhereDataYaml != "" {
			key := query.Name
			entries = append(entries, fmt.Sprintf("\t\"%s\":`%s`,", key, query.WhereDataYaml))
		}
	}

	if len(entries) == 0 {
		return ""
	}

	return fmt.Sprintf(`// WhereDataToYAMLCache WhereDataYAML缓存
var `+tableData.StructName+`WhereDataToYAMLCache = map[string]string{
%s
}`, strings.Join(entries, "\n"))
}

// generateInitFunction 生成 init 函数用于注册自定义 condition
func generateInitFunction(tableData *table.TableData) string {
	if !hasWhereDataToYAMLCache(tableData) {
		return ""
	}

	return `
var `+tableData.StructName+`ConditionMap = map[string]*conditonwhere.MaskWhereCondition{}

// 初始注册自定义函数的condition
func init() {
	for key, whereDataYaml := range `+tableData.StructName+`WhereDataToYAMLCache {
		var newData map[interface{}]interface{}
		yaml.Unmarshal([]byte(whereDataYaml), &newData)
		 `+tableData.StructName+`ConditionMap[key] = conditonwhere.ParseWhereCondition(newData)
	}
}
`
}

// GetModelTemplate 获取Model模板代码
func GetModelTemplate(tableData *table.TableData) string {
	var parts []string

	// 包声明
	parts = append(parts, "package model\n")

	// 导入语句
	imports := generateImports(tableData)
	if imports != "" {
		parts = append(parts, imports)
		parts = append(parts, "\n")
	}

	// 主结构体
	parts = append(parts, generateStruct(tableData))
	parts = append(parts, "\n\n")

	// 主键类型
	parts = append(parts, generatePrimaryKeyType(tableData))
	parts = append(parts, "\n\n")

	// TableName方法
	parts = append(parts, generateTableNameMethod(tableData))
	parts = append(parts, "\n\n")

	// Clone方法
	parts = append(parts, generateCloneMethod(tableData))
	parts = append(parts, "\n\n")

	// ToString方法
	parts = append(parts, generateToStringMethod(tableData))
	parts = append(parts, "\n\n")

	// AllowUpdateCols变量
	parts = append(parts, generateAllowUpdateCols(tableData))
	parts = append(parts, "\n\n")

	// IndexLeadingCols变量
	indexLeadingCols := generateIndexLeadingCols(tableData)
	if indexLeadingCols != "" {
		parts = append(parts, indexLeadingCols)
		parts = append(parts, "\n\n")
	}

	// Column结构体
	// parts = append(parts, generateColumnStruct(tableData))
	parts = append(parts, "\n\n")

	// 自定义查询代码
	queryCode := generateQueryCode(tableData)
	if queryCode != "" {
		parts = append(parts, queryCode)
	}

	// WhereDataToYAMLCache
	whereCache := generateWhereDataToYAMLCache(tableData)
	if whereCache != "" {
		parts = append(parts, "\n\n")
		parts = append(parts, whereCache)
	}

	// init 函数
	initFunc := generateInitFunction(tableData)
	if initFunc != "" {
		parts = append(parts, "\n\n")
		parts = append(parts, initFunc)
	}

	return strings.Join(parts, "")
}
