package model

// 模板内容
const ModelTemplate = `package model

{{- if .ModelTemplateData.ImportPackages}}
import (
{{range .ModelTemplateData.ImportPackages}}
	"{{.}}"
{{- end}}
{{- if .HasPage}}
	db "ag-core/contribute/agdb/gormdb"
{{- end}}
)
{{- else if .HasPage}}
import (
	db "ag-core/contribute/agdb/gormdb"
)
{{- else}}
import (
	"fmt"
)
{{- end}}

// {{.StructName}} 表模型
// AUTOGENERATED: DO NOT EDIT
type {{.StructName}} struct {
{{- range .Columns}}
	{{.JsonTag}} {{.GoType}} ` + "`" + `gorm:"{{.GormTag}}" json:"{{.JsonTag}}"` + "`" + `
{{- end}}
}

// TableName 返回表名
func ({{toLower .StructName}} *{{.StructName}}) TableName() string {
	return "{{.TableName}}"
}

// Clone 克隆对象
func ({{toLower .StructName}} *{{.StructName}}) Clone() *{{.StructName}} {
	if {{toLower .StructName}} == nil {
		return nil
	}
	return &{{.StructName}}{
{{- range .Columns}}
		{{.JsonTag}}: {{toLower $.StructName}}.{{.JsonTag}},
{{- end}}
	}
}

// ToString 转换为字符串
func ({{toLower .StructName}} *{{.StructName}}) ToString() string {
	if {{toLower .StructName}} == nil {
		return ""
	}
	return fmt.Sprintf("{{.StructName}}:(%+v)", *{{toLower $.StructName}})
}

// {{.StructName}}AllowUpdateCols 支持更新的列名列表
var {{.StructName}}AllowUpdateCols = []string{ {{range $index, $col := .AllowUpdateCols}}{{if $index}},{{end}}"{{$col}}"{{end}} }

{{- range .SelfQueries}}
{{$query := .}}
{{$table := $}}
{{$queryName := .Name}}
{{- if .HasPage}}
// {{$.StructName}}{{.Name}}Arg {{.Name}} 查询参数
type {{$.StructName}}{{.Name}}Arg struct {
	db.Page
{{- range $wc := .WhereColFields}}
{{$fieldName := $wc.FieldName}}
{{$isSlice := $wc.IsSlice}}
{{$colName := $wc.ColName}}
{{- range $col := $table.Columns}}
{{- if eq $col.Name $colName}}
{{- if $isSlice}}
	{{$fieldName}} []{{$col.GoType}}
{{- else}}
	{{$fieldName}} {{$col.GoType}}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
}

// ConvertToMap 将参数转换为map
func ({{toLower $.StructName}}{{.Name}}Arg *{{$.StructName}}{{.Name}}Arg) ConvertToMap() map[string]interface{} {
	if {{toLower $.StructName}}{{.Name}}Arg == nil {
		return nil
	}
	return map[string]interface{}{
		"Page": {{toLower $.StructName}}{{.Name}}Arg.Page,
{{- range $wc := .WhereColFields}}
		"{{$wc.FieldName}}": {{toLower $.StructName}}{{$queryName}}Arg.{{$wc.FieldName}},
{{- end}}
	}
}

{{- else}}
type {{$.StructName}}{{.Name}}Arg struct {
{{- range $wc := .WhereColFields}}
{{$fieldName := $wc.FieldName}}
{{$isSlice := $wc.IsSlice}}
{{$colName := $wc.ColName}}
{{- range $col := $table.Columns}}
{{- if eq $col.Name $colName}}
{{- if $isSlice}}
	{{$fieldName}} []{{$col.GoType}}
{{- else}}
	{{$fieldName}} {{$col.GoType}}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
}

// ConvertToMap 将参数转换为map
func ({{toLower $.StructName}}{{.Name}}Arg *{{$.StructName}}{{.Name}}Arg) ConvertToMap() map[string]interface{} {
	if {{toLower $.StructName}}{{.Name}}Arg == nil {
		return nil
	}
	return map[string]interface{}{
{{- range $wc := .WhereColFields}}
		"{{$wc.FieldName}}": {{toLower $.StructName}}{{$queryName}}Arg.{{$wc.FieldName}},
{{- end}}
	}
}

{{- end}}

{{- if .HasPage}}
// {{$.StructName}}{{.Name}}Res {{.Name}} 查询结果
type {{$.StructName}}{{.Name}}PageRes struct {
	db.PageResult
	{{- if eq .SelectFields "*"}}
	ResultList []*{{$.StructName}}
	{{- else }}
	ResultList []*{{$.StructName}}{{.Name}}Res
	{{- end}}
}
{{- end}}


{{- if not (eq .SelectFields "*")}}
type {{$.StructName}}{{.Name}}Res struct {
{{- range $.Columns}}
{{- if inArray $query .Name}}
	{{.JsonTag}} {{.GoType}}
{{- end}}
{{- end}}
}
{{- end}}
{{- end}}`
