package tpl

var version string = `// Code generated by {{.PluginName}}. DO NOT EDIT.
// Code generated by {{.PluginName}}. DO NOT EDIT.
// Code generated by {{.PluginName}}. DO NOT EDIT.
// Generate time: {{DateTimeNow}}
// versions:
//   - {{.PluginName}}: {{.Version}}
//   - protoc: {{.ProtocVersion}}
`

var pkgImport string = `
package {{ToLower .ServiceName}}
import (
	{{- range $path, $aliases := .Imports}}
		{{- if not $aliases}}
			"{{$path}}"
		{{- else}}
			{{- range $alias, $is := $aliases}}
				{{$alias}} "{{$path}}"
			{{- end}}
		{{- end}}
	{{- end}}
)
`
