package model
import (
	"fmt"
	"github.com/shopspring/decimal"
	"time"
)
// TmStudent 表模型
// AUTOGENERATED: DO NOT EDIT
type TmStudent struct {
	TenantId int64 `gorm:"column:tenant_id;primaryKey;not null" json:"TenantId"`
	StudentNo string `gorm:"column:student_no;primaryKey;not null;size:20" json:"StudentNo"`
	Name string `gorm:"column:name;size:20;index:tm_teacher_Name_IDX,priority:1" json:"Name"`
	Address string `gorm:"column:address;size:100;index:tm_teacher_Name_IDX,priority:2" json:"Address"`
	Phone string `gorm:"column:phone;size:11;index:tm_teacher_phone_IDX,priority:1" json:"Phone"`
	ClassId string `gorm:"column:class_id;size:2;index:tm_teacher_classid_IDX,priority:1" json:"ClassId"`
	CardNo string `gorm:"column:card_no;size:20;index:tm_teacher_name_IDX,priority:1" json:"CardNo"`
	Score decimal.Decimal `gorm:"column:score;type:decimal(10,2);precision:10;scale:2" json:"Score"`
	EnrollDate *time.Time `gorm:"column:enroll_date" json:"EnrollDate"`
	IsGraduate bool `gorm:"column:is_graduate" json:"IsGraduate"`
	JpaVersion int64 `gorm:"column:jpa_version" json:"JpaVersion"`
	CreateTime time.Time `gorm:"column:create_time;AUTOCREATETIME" json:"CreateTime"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;AUTOUPDATETIME" json:"LastUpdateTime"`
}

// TmStudentPrimarkey 多主键结构体
type TmStudentPrimarkey struct {
	TenantId int64
	StudentNo string
}

// TableName 返回表名
func (tmStudent *TmStudent) TableName() string {
	return "tm_student"
}

// Clone 克隆对象
func (tmStudent *TmStudent) Clone() *TmStudent {
	if tmStudent == nil {
		return nil
	}
	return &TmStudent{
		TenantId: tmStudent.TenantId,
		StudentNo: tmStudent.StudentNo,
		Name: tmStudent.Name,
		Address: tmStudent.Address,
		Phone: tmStudent.Phone,
		ClassId: tmStudent.ClassId,
		CardNo: tmStudent.CardNo,
		Score: tmStudent.Score,
		EnrollDate: tmStudent.EnrollDate,
		IsGraduate: tmStudent.IsGraduate,
		JpaVersion: tmStudent.JpaVersion,
		CreateTime: tmStudent.CreateTime,
		LastUpdateTime: tmStudent.LastUpdateTime,
	}
}

// ListZeroValueCols 列出零值列或非零值列
// filterPrimary: false-主键列正常处理 true-主键列被过滤掉
// filterIndex: false-索引列正常处理 true-索引列被过滤掉
// filterIsZero: false-只获取零值的列, true-只获取非零值的列
// filterSpecial: 是否过滤特殊列(jpaVersion/createTime/lastUpdateTime)
func (tmStudent *TmStudent) ListZeroValueCols(filterPrimary bool, filterIndex bool, filterIsZero bool, filterSpecial bool) ([]string, []interface{}, error) {
	if tmStudent == nil {
		return nil, nil, fmt.Errorf("tmStudent is nil")
	}

	var cols []string
	var vals []interface{}

 // generalColZeroVal 用于普通列的零值检查，避免重复代码
	var generalColZeroVal bool = false
	

	// TenantId - 主键，索引列
	if !filterPrimary {
		isZero := tmStudent.TenantId == 0
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "tenant_id")
			vals = append(vals, tmStudent.TenantId)
		}
	}

	// StudentNo - 主键，索引列
	if !filterPrimary {
		isZero := tmStudent.StudentNo == ""
		// false 保留零值 true 过滤零值
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "student_no")
			vals = append(vals, tmStudent.StudentNo)
		}
	}

	// Name - 索引列
	if !filterIndex {
		isZero := tmStudent.Name == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "name")
			vals = append(vals, tmStudent.Name)
		}
	}

	// Address - 索引列
	if !filterIndex {
		isZero := tmStudent.Address == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "address")
			vals = append(vals, tmStudent.Address)
		}
	}

	// Phone - 索引列
	if !filterIndex {
		isZero := tmStudent.Phone == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "phone")
			vals = append(vals, tmStudent.Phone)
		}
	}

	// ClassId - 索引列
	if !filterIndex {
		isZero := tmStudent.ClassId == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "class_id")
			vals = append(vals, tmStudent.ClassId)
		}
	}

	// CardNo - 索引列
	if !filterIndex {
		isZero := tmStudent.CardNo == ""
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "card_no")
			vals = append(vals, tmStudent.CardNo)
		}
	}

	// Score - 普通列
	generalColZeroVal = tmStudent.Score.IsZero()
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "score")
		vals = append(vals, tmStudent.Score)
	}

	// EnrollDate - 普通列
	generalColZeroVal = tmStudent.EnrollDate == nil
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "enroll_date")
		vals = append(vals, tmStudent.EnrollDate)
	}

	// IsGraduate - 普通列
	generalColZeroVal = !tmStudent.IsGraduate
	if (!filterIsZero && generalColZeroVal) || (filterIsZero && !generalColZeroVal) {
		cols = append(cols, "is_graduate")
		vals = append(vals, tmStudent.IsGraduate)
	}

	// JpaVersion - 特殊列，用于乐观锁
	if !filterSpecial {
		isZero := tmStudent.JpaVersion == 0
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "jpa_version")
			vals = append(vals, tmStudent.JpaVersion)
		}
	}

	// CreateTime - 特殊列，用于自动创建时间
	if !filterSpecial {
		isZero := tmStudent.CreateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "create_time")
			vals = append(vals, tmStudent.CreateTime)
		}
	}

	// LastUpdateTime - 特殊列，用于自动更新时间
	if !filterSpecial {
		isZero := tmStudent.LastUpdateTime.IsZero()
		if (!filterIsZero && isZero) || (filterIsZero && !isZero) {
			cols = append(cols, "last_update_time")
			vals = append(vals, tmStudent.LastUpdateTime)
		}
	}

	return cols, vals, nil
}

// ToString 转换为字符串
func (tmStudent *TmStudent) ToString() string {
	if tmStudent == nil {
		return ""
	}
	return fmt.Sprintf("TmStudent:(%+v)", *tmStudent)
}

// TmStudentAllowUpdateCols 支持更新的列名列表
var TmStudentAllowUpdateCols = []string{"class_id", "card_no"}

// TmStudentIndexLeadingCols 索引前导列，用于检查是否走了索引，避免全表扫描
// 列名必须和数据库表列名一致，区分大小写
var TmStudentIndexLeadingCols = []string{"tenant_id", "card_no", "phone", "class_id", "name"}



